# This application profile turns of the MSR global ledger integration so that
# the MSR can be used as a stand-alone service.

# Disable the ledger integration while developing
ledger:
    enabled: false