// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code ApplicationMessageHeader}
 */
public final class ApplicationMessageHeader extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ApplicationMessageHeader)
    ApplicationMessageHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ApplicationMessageHeader.class.getName());
  }
  // Use ApplicationMessageHeader.newBuilder() to construct.
  private ApplicationMessageHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ApplicationMessageHeader() {
    sender_ = "";
    qosProfile_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ApplicationMessageHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ApplicationMessageHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.ApplicationMessageHeader.class, net.maritimeconnectivity.mmtp.ApplicationMessageHeader.Builder.class);
  }

  private int bitField0_;
  private int subjectOrRecipientCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object subjectOrRecipient_;
  public enum SubjectOrRecipientCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SUBJECT(1),
    RECIPIENTS(2),
    SUBJECTORRECIPIENT_NOT_SET(0);
    private final int value;
    private SubjectOrRecipientCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SubjectOrRecipientCase valueOf(int value) {
      return forNumber(value);
    }

    public static SubjectOrRecipientCase forNumber(int value) {
      switch (value) {
        case 1: return SUBJECT;
        case 2: return RECIPIENTS;
        case 0: return SUBJECTORRECIPIENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SubjectOrRecipientCase
  getSubjectOrRecipientCase() {
    return SubjectOrRecipientCase.forNumber(
        subjectOrRecipientCase_);
  }

  public static final int SUBJECT_FIELD_NUMBER = 1;
  /**
   * <code>string subject = 1;</code>
   * @return Whether the subject field is set.
   */
  public boolean hasSubject() {
    return subjectOrRecipientCase_ == 1;
  }
  /**
   * <code>string subject = 1;</code>
   * @return The subject.
   */
  public java.lang.String getSubject() {
    java.lang.Object ref = "";
    if (subjectOrRecipientCase_ == 1) {
      ref = subjectOrRecipient_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (subjectOrRecipientCase_ == 1) {
        subjectOrRecipient_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string subject = 1;</code>
   * @return The bytes for subject.
   */
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    java.lang.Object ref = "";
    if (subjectOrRecipientCase_ == 1) {
      ref = subjectOrRecipient_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (subjectOrRecipientCase_ == 1) {
        subjectOrRecipient_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECIPIENTS_FIELD_NUMBER = 2;
  /**
   * <code>.Recipients recipients = 2;</code>
   * @return Whether the recipients field is set.
   */
  @java.lang.Override
  public boolean hasRecipients() {
    return subjectOrRecipientCase_ == 2;
  }
  /**
   * <code>.Recipients recipients = 2;</code>
   * @return The recipients.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Recipients getRecipients() {
    if (subjectOrRecipientCase_ == 2) {
       return (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_;
    }
    return net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
  }
  /**
   * <code>.Recipients recipients = 2;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.RecipientsOrBuilder getRecipientsOrBuilder() {
    if (subjectOrRecipientCase_ == 2) {
       return (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_;
    }
    return net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
  }

  public static final int EXPIRES_FIELD_NUMBER = 3;
  private long expires_ = 0L;
  /**
   * <code>int64 expires = 3;</code>
   * @return The expires.
   */
  @java.lang.Override
  public long getExpires() {
    return expires_;
  }

  public static final int SENDER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sender_ = "";
  /**
   * <code>string sender = 4;</code>
   * @return The sender.
   */
  @java.lang.Override
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <code>string sender = 4;</code>
   * @return The bytes for sender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QOSPROFILE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object qosProfile_ = "";
  /**
   * <code>optional string qosProfile = 5;</code>
   * @return Whether the qosProfile field is set.
   */
  @java.lang.Override
  public boolean hasQosProfile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string qosProfile = 5;</code>
   * @return The qosProfile.
   */
  @java.lang.Override
  public java.lang.String getQosProfile() {
    java.lang.Object ref = qosProfile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      qosProfile_ = s;
      return s;
    }
  }
  /**
   * <code>optional string qosProfile = 5;</code>
   * @return The bytes for qosProfile.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQosProfileBytes() {
    java.lang.Object ref = qosProfile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      qosProfile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODYSIZENUMBYTES_FIELD_NUMBER = 6;
  private int bodySizeNumBytes_ = 0;
  /**
   * <code>uint32 bodySizeNumBytes = 6;</code>
   * @return The bodySizeNumBytes.
   */
  @java.lang.Override
  public int getBodySizeNumBytes() {
    return bodySizeNumBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (subjectOrRecipientCase_ == 1) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, subjectOrRecipient_);
    }
    if (subjectOrRecipientCase_ == 2) {
      output.writeMessage(2, (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_);
    }
    if (expires_ != 0L) {
      output.writeInt64(3, expires_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sender_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, sender_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, qosProfile_);
    }
    if (bodySizeNumBytes_ != 0) {
      output.writeUInt32(6, bodySizeNumBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (subjectOrRecipientCase_ == 1) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, subjectOrRecipient_);
    }
    if (subjectOrRecipientCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_);
    }
    if (expires_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, expires_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sender_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, sender_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, qosProfile_);
    }
    if (bodySizeNumBytes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, bodySizeNumBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.ApplicationMessageHeader)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.ApplicationMessageHeader other = (net.maritimeconnectivity.mmtp.ApplicationMessageHeader) obj;

    if (getExpires()
        != other.getExpires()) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (hasQosProfile() != other.hasQosProfile()) return false;
    if (hasQosProfile()) {
      if (!getQosProfile()
          .equals(other.getQosProfile())) return false;
    }
    if (getBodySizeNumBytes()
        != other.getBodySizeNumBytes()) return false;
    if (!getSubjectOrRecipientCase().equals(other.getSubjectOrRecipientCase())) return false;
    switch (subjectOrRecipientCase_) {
      case 1:
        if (!getSubject()
            .equals(other.getSubject())) return false;
        break;
      case 2:
        if (!getRecipients()
            .equals(other.getRecipients())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXPIRES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpires());
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    if (hasQosProfile()) {
      hash = (37 * hash) + QOSPROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getQosProfile().hashCode();
    }
    hash = (37 * hash) + BODYSIZENUMBYTES_FIELD_NUMBER;
    hash = (53 * hash) + getBodySizeNumBytes();
    switch (subjectOrRecipientCase_) {
      case 1:
        hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getSubject().hashCode();
        break;
      case 2:
        hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getRecipients().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.ApplicationMessageHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ApplicationMessageHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApplicationMessageHeader)
      net.maritimeconnectivity.mmtp.ApplicationMessageHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ApplicationMessageHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ApplicationMessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.ApplicationMessageHeader.class, net.maritimeconnectivity.mmtp.ApplicationMessageHeader.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.ApplicationMessageHeader.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (recipientsBuilder_ != null) {
        recipientsBuilder_.clear();
      }
      expires_ = 0L;
      sender_ = "";
      qosProfile_ = "";
      bodySizeNumBytes_ = 0;
      subjectOrRecipientCase_ = 0;
      subjectOrRecipient_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ApplicationMessageHeader_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ApplicationMessageHeader getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.ApplicationMessageHeader.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ApplicationMessageHeader build() {
      net.maritimeconnectivity.mmtp.ApplicationMessageHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ApplicationMessageHeader buildPartial() {
      net.maritimeconnectivity.mmtp.ApplicationMessageHeader result = new net.maritimeconnectivity.mmtp.ApplicationMessageHeader(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.ApplicationMessageHeader result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.expires_ = expires_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sender_ = sender_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.qosProfile_ = qosProfile_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.bodySizeNumBytes_ = bodySizeNumBytes_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(net.maritimeconnectivity.mmtp.ApplicationMessageHeader result) {
      result.subjectOrRecipientCase_ = subjectOrRecipientCase_;
      result.subjectOrRecipient_ = this.subjectOrRecipient_;
      if (subjectOrRecipientCase_ == 2 &&
          recipientsBuilder_ != null) {
        result.subjectOrRecipient_ = recipientsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.ApplicationMessageHeader) {
        return mergeFrom((net.maritimeconnectivity.mmtp.ApplicationMessageHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.ApplicationMessageHeader other) {
      if (other == net.maritimeconnectivity.mmtp.ApplicationMessageHeader.getDefaultInstance()) return this;
      if (other.getExpires() != 0L) {
        setExpires(other.getExpires());
      }
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasQosProfile()) {
        qosProfile_ = other.qosProfile_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getBodySizeNumBytes() != 0) {
        setBodySizeNumBytes(other.getBodySizeNumBytes());
      }
      switch (other.getSubjectOrRecipientCase()) {
        case SUBJECT: {
          subjectOrRecipientCase_ = 1;
          subjectOrRecipient_ = other.subjectOrRecipient_;
          onChanged();
          break;
        }
        case RECIPIENTS: {
          mergeRecipients(other.getRecipients());
          break;
        }
        case SUBJECTORRECIPIENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              subjectOrRecipientCase_ = 1;
              subjectOrRecipient_ = s;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRecipientsFieldBuilder().getBuilder(),
                  extensionRegistry);
              subjectOrRecipientCase_ = 2;
              break;
            } // case 18
            case 24: {
              expires_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              sender_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              qosProfile_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              bodySizeNumBytes_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int subjectOrRecipientCase_ = 0;
    private java.lang.Object subjectOrRecipient_;
    public SubjectOrRecipientCase
        getSubjectOrRecipientCase() {
      return SubjectOrRecipientCase.forNumber(
          subjectOrRecipientCase_);
    }

    public Builder clearSubjectOrRecipient() {
      subjectOrRecipientCase_ = 0;
      subjectOrRecipient_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>string subject = 1;</code>
     * @return Whether the subject field is set.
     */
    @java.lang.Override
    public boolean hasSubject() {
      return subjectOrRecipientCase_ == 1;
    }
    /**
     * <code>string subject = 1;</code>
     * @return The subject.
     */
    @java.lang.Override
    public java.lang.String getSubject() {
      java.lang.Object ref = "";
      if (subjectOrRecipientCase_ == 1) {
        ref = subjectOrRecipient_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (subjectOrRecipientCase_ == 1) {
          subjectOrRecipient_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject = 1;</code>
     * @return The bytes for subject.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = "";
      if (subjectOrRecipientCase_ == 1) {
        ref = subjectOrRecipient_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (subjectOrRecipientCase_ == 1) {
          subjectOrRecipient_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject = 1;</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subjectOrRecipientCase_ = 1;
      subjectOrRecipient_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      if (subjectOrRecipientCase_ == 1) {
        subjectOrRecipientCase_ = 0;
        subjectOrRecipient_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string subject = 1;</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subjectOrRecipientCase_ = 1;
      subjectOrRecipient_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Recipients, net.maritimeconnectivity.mmtp.Recipients.Builder, net.maritimeconnectivity.mmtp.RecipientsOrBuilder> recipientsBuilder_;
    /**
     * <code>.Recipients recipients = 2;</code>
     * @return Whether the recipients field is set.
     */
    @java.lang.Override
    public boolean hasRecipients() {
      return subjectOrRecipientCase_ == 2;
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     * @return The recipients.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Recipients getRecipients() {
      if (recipientsBuilder_ == null) {
        if (subjectOrRecipientCase_ == 2) {
          return (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_;
        }
        return net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
      } else {
        if (subjectOrRecipientCase_ == 2) {
          return recipientsBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
      }
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    public Builder setRecipients(net.maritimeconnectivity.mmtp.Recipients value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subjectOrRecipient_ = value;
        onChanged();
      } else {
        recipientsBuilder_.setMessage(value);
      }
      subjectOrRecipientCase_ = 2;
      return this;
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    public Builder setRecipients(
        net.maritimeconnectivity.mmtp.Recipients.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        subjectOrRecipient_ = builderForValue.build();
        onChanged();
      } else {
        recipientsBuilder_.setMessage(builderForValue.build());
      }
      subjectOrRecipientCase_ = 2;
      return this;
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    public Builder mergeRecipients(net.maritimeconnectivity.mmtp.Recipients value) {
      if (recipientsBuilder_ == null) {
        if (subjectOrRecipientCase_ == 2 &&
            subjectOrRecipient_ != net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance()) {
          subjectOrRecipient_ = net.maritimeconnectivity.mmtp.Recipients.newBuilder((net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_)
              .mergeFrom(value).buildPartial();
        } else {
          subjectOrRecipient_ = value;
        }
        onChanged();
      } else {
        if (subjectOrRecipientCase_ == 2) {
          recipientsBuilder_.mergeFrom(value);
        } else {
          recipientsBuilder_.setMessage(value);
        }
      }
      subjectOrRecipientCase_ = 2;
      return this;
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    public Builder clearRecipients() {
      if (recipientsBuilder_ == null) {
        if (subjectOrRecipientCase_ == 2) {
          subjectOrRecipientCase_ = 0;
          subjectOrRecipient_ = null;
          onChanged();
        }
      } else {
        if (subjectOrRecipientCase_ == 2) {
          subjectOrRecipientCase_ = 0;
          subjectOrRecipient_ = null;
        }
        recipientsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    public net.maritimeconnectivity.mmtp.Recipients.Builder getRecipientsBuilder() {
      return getRecipientsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.RecipientsOrBuilder getRecipientsOrBuilder() {
      if ((subjectOrRecipientCase_ == 2) && (recipientsBuilder_ != null)) {
        return recipientsBuilder_.getMessageOrBuilder();
      } else {
        if (subjectOrRecipientCase_ == 2) {
          return (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_;
        }
        return net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
      }
    }
    /**
     * <code>.Recipients recipients = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Recipients, net.maritimeconnectivity.mmtp.Recipients.Builder, net.maritimeconnectivity.mmtp.RecipientsOrBuilder> 
        getRecipientsFieldBuilder() {
      if (recipientsBuilder_ == null) {
        if (!(subjectOrRecipientCase_ == 2)) {
          subjectOrRecipient_ = net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
        }
        recipientsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Recipients, net.maritimeconnectivity.mmtp.Recipients.Builder, net.maritimeconnectivity.mmtp.RecipientsOrBuilder>(
                (net.maritimeconnectivity.mmtp.Recipients) subjectOrRecipient_,
                getParentForChildren(),
                isClean());
        subjectOrRecipient_ = null;
      }
      subjectOrRecipientCase_ = 2;
      onChanged();
      return recipientsBuilder_;
    }

    private long expires_ ;
    /**
     * <code>int64 expires = 3;</code>
     * @return The expires.
     */
    @java.lang.Override
    public long getExpires() {
      return expires_;
    }
    /**
     * <code>int64 expires = 3;</code>
     * @param value The expires to set.
     * @return This builder for chaining.
     */
    public Builder setExpires(long value) {

      expires_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expires = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpires() {
      bitField0_ = (bitField0_ & ~0x00000004);
      expires_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sender_ = "";
    /**
     * <code>string sender = 4;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender = 4;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender = 4;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sender_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      sender_ = getDefaultInstance().getSender();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 4;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sender_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object qosProfile_ = "";
    /**
     * <code>optional string qosProfile = 5;</code>
     * @return Whether the qosProfile field is set.
     */
    public boolean hasQosProfile() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string qosProfile = 5;</code>
     * @return The qosProfile.
     */
    public java.lang.String getQosProfile() {
      java.lang.Object ref = qosProfile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        qosProfile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string qosProfile = 5;</code>
     * @return The bytes for qosProfile.
     */
    public com.google.protobuf.ByteString
        getQosProfileBytes() {
      java.lang.Object ref = qosProfile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qosProfile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string qosProfile = 5;</code>
     * @param value The qosProfile to set.
     * @return This builder for chaining.
     */
    public Builder setQosProfile(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      qosProfile_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string qosProfile = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearQosProfile() {
      qosProfile_ = getDefaultInstance().getQosProfile();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string qosProfile = 5;</code>
     * @param value The bytes for qosProfile to set.
     * @return This builder for chaining.
     */
    public Builder setQosProfileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      qosProfile_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int bodySizeNumBytes_ ;
    /**
     * <code>uint32 bodySizeNumBytes = 6;</code>
     * @return The bodySizeNumBytes.
     */
    @java.lang.Override
    public int getBodySizeNumBytes() {
      return bodySizeNumBytes_;
    }
    /**
     * <code>uint32 bodySizeNumBytes = 6;</code>
     * @param value The bodySizeNumBytes to set.
     * @return This builder for chaining.
     */
    public Builder setBodySizeNumBytes(int value) {

      bodySizeNumBytes_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 bodySizeNumBytes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBodySizeNumBytes() {
      bitField0_ = (bitField0_ & ~0x00000020);
      bodySizeNumBytes_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ApplicationMessageHeader)
  }

  // @@protoc_insertion_point(class_scope:ApplicationMessageHeader)
  private static final net.maritimeconnectivity.mmtp.ApplicationMessageHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.ApplicationMessageHeader();
  }

  public static net.maritimeconnectivity.mmtp.ApplicationMessageHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplicationMessageHeader>
      PARSER = new com.google.protobuf.AbstractParser<ApplicationMessageHeader>() {
    @java.lang.Override
    public ApplicationMessageHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ApplicationMessageHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApplicationMessageHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ApplicationMessageHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

