// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code Connect}
 */
public final class Connect extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Connect)
    ConnectOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Connect.class.getName());
  }
  // Use Connect.newBuilder() to construct.
  private Connect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Connect() {
    ownMrn_ = "";
    reconnectToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Connect_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Connect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.Connect.class, net.maritimeconnectivity.mmtp.Connect.Builder.class);
  }

  private int bitField0_;
  public static final int OWNMRN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ownMrn_ = "";
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return Whether the ownMrn field is set.
   */
  @java.lang.Override
  public boolean hasOwnMrn() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return The ownMrn.
   */
  @java.lang.Override
  public java.lang.String getOwnMrn() {
    java.lang.Object ref = ownMrn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownMrn_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return The bytes for ownMrn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnMrnBytes() {
    java.lang.Object ref = ownMrn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownMrn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECONNECTTOKEN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reconnectToken_ = "";
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return Whether the reconnectToken field is set.
   */
  @java.lang.Override
  public boolean hasReconnectToken() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return The reconnectToken.
   */
  @java.lang.Override
  public java.lang.String getReconnectToken() {
    java.lang.Object ref = reconnectToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reconnectToken_ = s;
      return s;
    }
  }
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return The bytes for reconnectToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReconnectTokenBytes() {
    java.lang.Object ref = reconnectToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reconnectToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ownMrn_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, reconnectToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ownMrn_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, reconnectToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.Connect)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.Connect other = (net.maritimeconnectivity.mmtp.Connect) obj;

    if (hasOwnMrn() != other.hasOwnMrn()) return false;
    if (hasOwnMrn()) {
      if (!getOwnMrn()
          .equals(other.getOwnMrn())) return false;
    }
    if (hasReconnectToken() != other.hasReconnectToken()) return false;
    if (hasReconnectToken()) {
      if (!getReconnectToken()
          .equals(other.getReconnectToken())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOwnMrn()) {
      hash = (37 * hash) + OWNMRN_FIELD_NUMBER;
      hash = (53 * hash) + getOwnMrn().hashCode();
    }
    if (hasReconnectToken()) {
      hash = (37 * hash) + RECONNECTTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getReconnectToken().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.Connect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.Connect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Connect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.Connect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Connect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Connect)
      net.maritimeconnectivity.mmtp.ConnectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Connect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Connect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.Connect.class, net.maritimeconnectivity.mmtp.Connect.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.Connect.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ownMrn_ = "";
      reconnectToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Connect_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Connect getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Connect build() {
      net.maritimeconnectivity.mmtp.Connect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Connect buildPartial() {
      net.maritimeconnectivity.mmtp.Connect result = new net.maritimeconnectivity.mmtp.Connect(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.Connect result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ownMrn_ = ownMrn_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reconnectToken_ = reconnectToken_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.Connect) {
        return mergeFrom((net.maritimeconnectivity.mmtp.Connect)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.Connect other) {
      if (other == net.maritimeconnectivity.mmtp.Connect.getDefaultInstance()) return this;
      if (other.hasOwnMrn()) {
        ownMrn_ = other.ownMrn_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasReconnectToken()) {
        reconnectToken_ = other.reconnectToken_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ownMrn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              reconnectToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ownMrn_ = "";
    /**
     * <code>optional string ownMrn = 1;</code>
     * @return Whether the ownMrn field is set.
     */
    public boolean hasOwnMrn() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string ownMrn = 1;</code>
     * @return The ownMrn.
     */
    public java.lang.String getOwnMrn() {
      java.lang.Object ref = ownMrn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownMrn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ownMrn = 1;</code>
     * @return The bytes for ownMrn.
     */
    public com.google.protobuf.ByteString
        getOwnMrnBytes() {
      java.lang.Object ref = ownMrn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownMrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ownMrn = 1;</code>
     * @param value The ownMrn to set.
     * @return This builder for chaining.
     */
    public Builder setOwnMrn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ownMrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ownMrn = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnMrn() {
      ownMrn_ = getDefaultInstance().getOwnMrn();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string ownMrn = 1;</code>
     * @param value The bytes for ownMrn to set.
     * @return This builder for chaining.
     */
    public Builder setOwnMrnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ownMrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object reconnectToken_ = "";
    /**
     * <code>optional string reconnectToken = 2;</code>
     * @return Whether the reconnectToken field is set.
     */
    public boolean hasReconnectToken() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string reconnectToken = 2;</code>
     * @return The reconnectToken.
     */
    public java.lang.String getReconnectToken() {
      java.lang.Object ref = reconnectToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reconnectToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string reconnectToken = 2;</code>
     * @return The bytes for reconnectToken.
     */
    public com.google.protobuf.ByteString
        getReconnectTokenBytes() {
      java.lang.Object ref = reconnectToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reconnectToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reconnectToken = 2;</code>
     * @param value The reconnectToken to set.
     * @return This builder for chaining.
     */
    public Builder setReconnectToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reconnectToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reconnectToken = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReconnectToken() {
      reconnectToken_ = getDefaultInstance().getReconnectToken();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string reconnectToken = 2;</code>
     * @param value The bytes for reconnectToken to set.
     * @return This builder for chaining.
     */
    public Builder setReconnectTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reconnectToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Connect)
  }

  // @@protoc_insertion_point(class_scope:Connect)
  private static final net.maritimeconnectivity.mmtp.Connect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.Connect();
  }

  public static net.maritimeconnectivity.mmtp.Connect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Connect>
      PARSER = new com.google.protobuf.AbstractParser<Connect>() {
    @java.lang.Override
    public Connect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Connect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Connect> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Connect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

