// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface DisconnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Disconnect)
    com.google.protobuf.MessageOrBuilder {
}
