// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface MessageMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.ApplicationMessageHeader header = 2;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.ApplicationMessageHeader header = 2;</code>
   * @return The header.
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageHeader getHeader();
  /**
   * <code>.ApplicationMessageHeader header = 2;</code>
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageHeaderOrBuilder getHeaderOrBuilder();
}
