// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface MessageContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.ApplicationMessage msg = 2;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.ApplicationMessage msg = 2;</code>
   * @return The msg.
   */
  net.maritimeconnectivity.mmtp.ApplicationMessage getMsg();
  /**
   * <code>.ApplicationMessage msg = 2;</code>
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageOrBuilder getMsgOrBuilder();
}
