// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code MmtpMessage}
 */
public final class MmtpMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:MmtpMessage)
    MmtpMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MmtpMessage.class.getName());
  }
  // Use MmtpMessage.newBuilder() to construct.
  private MmtpMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MmtpMessage() {
    msgType_ = 0;
    uuid_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_MmtpMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_MmtpMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.MmtpMessage.class, net.maritimeconnectivity.mmtp.MmtpMessage.Builder.class);
  }

  private int bodyCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PROTOCOLMESSAGE(3),
    RESPONSEMESSAGE(4),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 3: return PROTOCOLMESSAGE;
        case 4: return RESPONSEMESSAGE;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int MSGTYPE_FIELD_NUMBER = 1;
  private int msgType_ = 0;
  /**
   * <code>.MsgType msgType = 1;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  @java.lang.Override public int getMsgTypeValue() {
    return msgType_;
  }
  /**
   * <code>.MsgType msgType = 1;</code>
   * @return The msgType.
   */
  @java.lang.Override public net.maritimeconnectivity.mmtp.MsgType getMsgType() {
    net.maritimeconnectivity.mmtp.MsgType result = net.maritimeconnectivity.mmtp.MsgType.forNumber(msgType_);
    return result == null ? net.maritimeconnectivity.mmtp.MsgType.UNRECOGNIZED : result;
  }

  public static final int UUID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uuid_ = "";
  /**
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOLMESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>.ProtocolMessage protocolMessage = 3;</code>
   * @return Whether the protocolMessage field is set.
   */
  @java.lang.Override
  public boolean hasProtocolMessage() {
    return bodyCase_ == 3;
  }
  /**
   * <code>.ProtocolMessage protocolMessage = 3;</code>
   * @return The protocolMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ProtocolMessage getProtocolMessage() {
    if (bodyCase_ == 3) {
       return (net.maritimeconnectivity.mmtp.ProtocolMessage) body_;
    }
    return net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
  }
  /**
   * <code>.ProtocolMessage protocolMessage = 3;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder getProtocolMessageOrBuilder() {
    if (bodyCase_ == 3) {
       return (net.maritimeconnectivity.mmtp.ProtocolMessage) body_;
    }
    return net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
  }

  public static final int RESPONSEMESSAGE_FIELD_NUMBER = 4;
  /**
   * <code>.ResponseMessage responseMessage = 4;</code>
   * @return Whether the responseMessage field is set.
   */
  @java.lang.Override
  public boolean hasResponseMessage() {
    return bodyCase_ == 4;
  }
  /**
   * <code>.ResponseMessage responseMessage = 4;</code>
   * @return The responseMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ResponseMessage getResponseMessage() {
    if (bodyCase_ == 4) {
       return (net.maritimeconnectivity.mmtp.ResponseMessage) body_;
    }
    return net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
  }
  /**
   * <code>.ResponseMessage responseMessage = 4;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder getResponseMessageOrBuilder() {
    if (bodyCase_ == 4) {
       return (net.maritimeconnectivity.mmtp.ResponseMessage) body_;
    }
    return net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgType_ != net.maritimeconnectivity.mmtp.MsgType.UNSPECIFIED_MESSAGE.getNumber()) {
      output.writeEnum(1, msgType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, uuid_);
    }
    if (bodyCase_ == 3) {
      output.writeMessage(3, (net.maritimeconnectivity.mmtp.ProtocolMessage) body_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (net.maritimeconnectivity.mmtp.ResponseMessage) body_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgType_ != net.maritimeconnectivity.mmtp.MsgType.UNSPECIFIED_MESSAGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, msgType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, uuid_);
    }
    if (bodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (net.maritimeconnectivity.mmtp.ProtocolMessage) body_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (net.maritimeconnectivity.mmtp.ResponseMessage) body_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.MmtpMessage)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.MmtpMessage other = (net.maritimeconnectivity.mmtp.MmtpMessage) obj;

    if (msgType_ != other.msgType_) return false;
    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (!getBodyCase().equals(other.getBodyCase())) return false;
    switch (bodyCase_) {
      case 3:
        if (!getProtocolMessage()
            .equals(other.getProtocolMessage())) return false;
        break;
      case 4:
        if (!getResponseMessage()
            .equals(other.getResponseMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + msgType_;
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    switch (bodyCase_) {
      case 3:
        hash = (37 * hash) + PROTOCOLMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolMessage().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getResponseMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.MmtpMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.MmtpMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.MmtpMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.MmtpMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MmtpMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MmtpMessage)
      net.maritimeconnectivity.mmtp.MmtpMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_MmtpMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_MmtpMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.MmtpMessage.class, net.maritimeconnectivity.mmtp.MmtpMessage.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.MmtpMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      msgType_ = 0;
      uuid_ = "";
      if (protocolMessageBuilder_ != null) {
        protocolMessageBuilder_.clear();
      }
      if (responseMessageBuilder_ != null) {
        responseMessageBuilder_.clear();
      }
      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_MmtpMessage_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.MmtpMessage getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.MmtpMessage.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.MmtpMessage build() {
      net.maritimeconnectivity.mmtp.MmtpMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.MmtpMessage buildPartial() {
      net.maritimeconnectivity.mmtp.MmtpMessage result = new net.maritimeconnectivity.mmtp.MmtpMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.MmtpMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.msgType_ = msgType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.uuid_ = uuid_;
      }
    }

    private void buildPartialOneofs(net.maritimeconnectivity.mmtp.MmtpMessage result) {
      result.bodyCase_ = bodyCase_;
      result.body_ = this.body_;
      if (bodyCase_ == 3 &&
          protocolMessageBuilder_ != null) {
        result.body_ = protocolMessageBuilder_.build();
      }
      if (bodyCase_ == 4 &&
          responseMessageBuilder_ != null) {
        result.body_ = responseMessageBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.MmtpMessage) {
        return mergeFrom((net.maritimeconnectivity.mmtp.MmtpMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.MmtpMessage other) {
      if (other == net.maritimeconnectivity.mmtp.MmtpMessage.getDefaultInstance()) return this;
      if (other.msgType_ != 0) {
        setMsgTypeValue(other.getMsgTypeValue());
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      switch (other.getBodyCase()) {
        case PROTOCOLMESSAGE: {
          mergeProtocolMessage(other.getProtocolMessage());
          break;
        }
        case RESPONSEMESSAGE: {
          mergeResponseMessage(other.getResponseMessage());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              msgType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              uuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getProtocolMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getResponseMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int msgType_ = 0;
    /**
     * <code>.MsgType msgType = 1;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.MsgType msgType = 1;</code>
     * @param value The enum numeric value on the wire for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeValue(int value) {
      msgType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.MsgType msgType = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.MsgType getMsgType() {
      net.maritimeconnectivity.mmtp.MsgType result = net.maritimeconnectivity.mmtp.MsgType.forNumber(msgType_);
      return result == null ? net.maritimeconnectivity.mmtp.MsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.MsgType msgType = 1;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(net.maritimeconnectivity.mmtp.MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      msgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.MsgType msgType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      uuid_ = getDefaultInstance().getUuid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.ProtocolMessage, net.maritimeconnectivity.mmtp.ProtocolMessage.Builder, net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder> protocolMessageBuilder_;
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     * @return Whether the protocolMessage field is set.
     */
    @java.lang.Override
    public boolean hasProtocolMessage() {
      return bodyCase_ == 3;
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     * @return The protocolMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ProtocolMessage getProtocolMessage() {
      if (protocolMessageBuilder_ == null) {
        if (bodyCase_ == 3) {
          return (net.maritimeconnectivity.mmtp.ProtocolMessage) body_;
        }
        return net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
      } else {
        if (bodyCase_ == 3) {
          return protocolMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    public Builder setProtocolMessage(net.maritimeconnectivity.mmtp.ProtocolMessage value) {
      if (protocolMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        protocolMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    public Builder setProtocolMessage(
        net.maritimeconnectivity.mmtp.ProtocolMessage.Builder builderForValue) {
      if (protocolMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        protocolMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    public Builder mergeProtocolMessage(net.maritimeconnectivity.mmtp.ProtocolMessage value) {
      if (protocolMessageBuilder_ == null) {
        if (bodyCase_ == 3 &&
            body_ != net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.ProtocolMessage.newBuilder((net.maritimeconnectivity.mmtp.ProtocolMessage) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 3) {
          protocolMessageBuilder_.mergeFrom(value);
        } else {
          protocolMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    public Builder clearProtocolMessage() {
      if (protocolMessageBuilder_ == null) {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
        }
        protocolMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    public net.maritimeconnectivity.mmtp.ProtocolMessage.Builder getProtocolMessageBuilder() {
      return getProtocolMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder getProtocolMessageOrBuilder() {
      if ((bodyCase_ == 3) && (protocolMessageBuilder_ != null)) {
        return protocolMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 3) {
          return (net.maritimeconnectivity.mmtp.ProtocolMessage) body_;
        }
        return net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ProtocolMessage protocolMessage = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.ProtocolMessage, net.maritimeconnectivity.mmtp.ProtocolMessage.Builder, net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder> 
        getProtocolMessageFieldBuilder() {
      if (protocolMessageBuilder_ == null) {
        if (!(bodyCase_ == 3)) {
          body_ = net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
        }
        protocolMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.ProtocolMessage, net.maritimeconnectivity.mmtp.ProtocolMessage.Builder, net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder>(
                (net.maritimeconnectivity.mmtp.ProtocolMessage) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 3;
      onChanged();
      return protocolMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.ResponseMessage, net.maritimeconnectivity.mmtp.ResponseMessage.Builder, net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder> responseMessageBuilder_;
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     * @return Whether the responseMessage field is set.
     */
    @java.lang.Override
    public boolean hasResponseMessage() {
      return bodyCase_ == 4;
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     * @return The responseMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ResponseMessage getResponseMessage() {
      if (responseMessageBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (net.maritimeconnectivity.mmtp.ResponseMessage) body_;
        }
        return net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return responseMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    public Builder setResponseMessage(net.maritimeconnectivity.mmtp.ResponseMessage value) {
      if (responseMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        responseMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    public Builder setResponseMessage(
        net.maritimeconnectivity.mmtp.ResponseMessage.Builder builderForValue) {
      if (responseMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        responseMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    public Builder mergeResponseMessage(net.maritimeconnectivity.mmtp.ResponseMessage value) {
      if (responseMessageBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.ResponseMessage.newBuilder((net.maritimeconnectivity.mmtp.ResponseMessage) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          responseMessageBuilder_.mergeFrom(value);
        } else {
          responseMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    public Builder clearResponseMessage() {
      if (responseMessageBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        responseMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.ResponseMessage.Builder getResponseMessageBuilder() {
      return getResponseMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder getResponseMessageOrBuilder() {
      if ((bodyCase_ == 4) && (responseMessageBuilder_ != null)) {
        return responseMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (net.maritimeconnectivity.mmtp.ResponseMessage) body_;
        }
        return net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.ResponseMessage responseMessage = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.ResponseMessage, net.maritimeconnectivity.mmtp.ResponseMessage.Builder, net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder> 
        getResponseMessageFieldBuilder() {
      if (responseMessageBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
        }
        responseMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.ResponseMessage, net.maritimeconnectivity.mmtp.ResponseMessage.Builder, net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder>(
                (net.maritimeconnectivity.mmtp.ResponseMessage) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();
      return responseMessageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:MmtpMessage)
  }

  // @@protoc_insertion_point(class_scope:MmtpMessage)
  private static final net.maritimeconnectivity.mmtp.MmtpMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.MmtpMessage();
  }

  public static net.maritimeconnectivity.mmtp.MmtpMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MmtpMessage>
      PARSER = new com.google.protobuf.AbstractParser<MmtpMessage>() {
    @java.lang.Override
    public MmtpMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MmtpMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MmtpMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MmtpMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

