// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public final class Mmtp {
  private Mmtp() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Mmtp.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationMessageHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationMessageHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Recipients_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Recipients_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MmtpMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MmtpMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscribe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Subscribe_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unsubscribe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Unsubscribe_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Send_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Send_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Receive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Receive_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Filter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fetch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Fetch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Disconnect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Disconnect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Connect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Connect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmmtp.proto\"`\n\022ApplicationMessage\022)\n\006he" +
      "ader\030\001 \001(\0132\031.ApplicationMessageHeader\022\014\n" +
      "\004body\030\002 \001(\014\022\021\n\tsignature\030\003 \001(\014\"\311\001\n\030Appli" +
      "cationMessageHeader\022\021\n\007subject\030\001 \001(\tH\000\022!" +
      "\n\nrecipients\030\002 \001(\0132\013.RecipientsH\000\022\017\n\007exp" +
      "ires\030\003 \001(\003\022\016\n\006sender\030\004 \001(\t\022\027\n\nqosProfile" +
      "\030\005 \001(\tH\001\210\001\001\022\030\n\020bodySizeNumBytes\030\006 \001(\rB\024\n" +
      "\022SubjectOrRecipientB\r\n\013_qosProfile\" \n\nRe" +
      "cipients\022\022\n\nrecipients\030\001 \003(\t\"\230\001\n\013MmtpMes" +
      "sage\022\031\n\007msgType\030\001 \001(\0162\010.MsgType\022\014\n\004uuid\030" +
      "\002 \001(\t\022+\n\017protocolMessage\030\003 \001(\0132\020.Protoco" +
      "lMessageH\000\022+\n\017responseMessage\030\004 \001(\0132\020.Re" +
      "sponseMessageH\000B\006\n\004body\"\356\002\n\017ProtocolMess" +
      "age\022-\n\017protocolMsgType\030\001 \001(\0162\024.ProtocolM" +
      "essageType\022&\n\020subscribeMessage\030\002 \001(\0132\n.S" +
      "ubscribeH\000\022*\n\022unsubscribeMessage\030\003 \001(\0132\014" +
      ".UnsubscribeH\000\022\034\n\013sendMessage\030\004 \001(\0132\005.Se" +
      "ndH\000\022\"\n\016receiveMessage\030\005 \001(\0132\010.ReceiveH\000" +
      "\022\036\n\014fetchMessage\030\006 \001(\0132\006.FetchH\000\022(\n\021disc" +
      "onnectMessage\030\007 \001(\0132\013.DisconnectH\000\022\"\n\016co" +
      "nnectMessage\030\010 \001(\0132\010.ConnectH\000\022 \n\rnotify" +
      "Message\030\t \001(\0132\007.NotifyH\000B\006\n\004body\"S\n\tSubs" +
      "cribe\022\021\n\007subject\030\001 \001(\tH\000\022\030\n\016directMessag" +
      "es\030\002 \001(\010H\000B\031\n\027subjectOrDirectMessages\"U\n" +
      "\013Unsubscribe\022\021\n\007subject\030\001 \001(\tH\000\022\030\n\016direc" +
      "tMessages\030\002 \001(\010H\000B\031\n\027subjectOrDirectMess" +
      "ages\"7\n\004Send\022/\n\022applicationMessage\030\001 \001(\013" +
      "2\023.ApplicationMessage\"2\n\007Receive\022\034\n\006filt" +
      "er\030\001 \001(\0132\007.FilterH\000\210\001\001B\t\n\007_filter\"\036\n\006Fil" +
      "ter\022\024\n\014messageUuids\030\001 \003(\t\"\007\n\005Fetch\"\014\n\nDi" +
      "sconnect\"Y\n\007Connect\022\023\n\006ownMrn\030\001 \001(\tH\000\210\001\001" +
      "\022\033\n\016reconnectToken\030\002 \001(\tH\001\210\001\001B\t\n\007_ownMrn" +
      "B\021\n\017_reconnectToken\"3\n\006Notify\022)\n\017message" +
      "Metadata\030\001 \003(\0132\020.MessageMetadata\"\366\001\n\017Res" +
      "ponseMessage\022\026\n\016responseToUuid\030\001 \001(\t\022\037\n\010" +
      "response\030\002 \001(\0162\r.ResponseEnum\022\027\n\nreasonT" +
      "ext\030\003 \001(\tH\000\210\001\001\022)\n\017messageMetadata\030\004 \003(\0132" +
      "\020.MessageMetadata\022\'\n\016messageContent\030\005 \003(" +
      "\0132\017.MessageContent\022\033\n\016reconnectToken\030\006 \001" +
      "(\tH\001\210\001\001B\r\n\013_reasonTextB\021\n\017_reconnectToke" +
      "n\"J\n\017MessageMetadata\022\014\n\004uuid\030\001 \001(\t\022)\n\006he" +
      "ader\030\002 \001(\0132\031.ApplicationMessageHeader\"@\n" +
      "\016MessageContent\022\014\n\004uuid\030\001 \001(\t\022 \n\003msg\030\002 \001" +
      "(\0132\023.ApplicationMessage*N\n\007MsgType\022\027\n\023UN" +
      "SPECIFIED_MESSAGE\020\000\022\024\n\020PROTOCOL_MESSAGE\020" +
      "\001\022\024\n\020RESPONSE_MESSAGE\020\002*\321\001\n\023ProtocolMess" +
      "ageType\022\017\n\013UNSPECIFIED\020\000\022\025\n\021SUBSCRIBE_ME" +
      "SSAGE\020\001\022\027\n\023UNSUBSCRIBE_MESSAGE\020\002\022\020\n\014SEND" +
      "_MESSAGE\020\003\022\023\n\017RECEIVE_MESSAGE\020\004\022\021\n\rFETCH" +
      "_MESSAGE\020\005\022\026\n\022DISCONNECT_MESSAGE\020\006\022\023\n\017CO" +
      "NNECT_MESSAGE\020\007\022\022\n\016NOTIFY_MESSAGE\020\010*=\n\014R" +
      "esponseEnum\022\030\n\024UNSPECIFIED_RESPONSE\020\000\022\010\n" +
      "\004GOOD\020\001\022\t\n\005ERROR\020\002B!\n\035net.maritimeconnec" +
      "tivity.mmtpP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ApplicationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApplicationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationMessage_descriptor,
        new java.lang.String[] { "Header", "Body", "Signature", });
    internal_static_ApplicationMessageHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ApplicationMessageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationMessageHeader_descriptor,
        new java.lang.String[] { "Subject", "Recipients", "Expires", "Sender", "QosProfile", "BodySizeNumBytes", "SubjectOrRecipient", });
    internal_static_Recipients_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Recipients_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Recipients_descriptor,
        new java.lang.String[] { "Recipients", });
    internal_static_MmtpMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MmtpMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MmtpMessage_descriptor,
        new java.lang.String[] { "MsgType", "Uuid", "ProtocolMessage", "ResponseMessage", "Body", });
    internal_static_ProtocolMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ProtocolMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtocolMessage_descriptor,
        new java.lang.String[] { "ProtocolMsgType", "SubscribeMessage", "UnsubscribeMessage", "SendMessage", "ReceiveMessage", "FetchMessage", "DisconnectMessage", "ConnectMessage", "NotifyMessage", "Body", });
    internal_static_Subscribe_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Subscribe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Subscribe_descriptor,
        new java.lang.String[] { "Subject", "DirectMessages", "SubjectOrDirectMessages", });
    internal_static_Unsubscribe_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Unsubscribe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Unsubscribe_descriptor,
        new java.lang.String[] { "Subject", "DirectMessages", "SubjectOrDirectMessages", });
    internal_static_Send_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Send_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Send_descriptor,
        new java.lang.String[] { "ApplicationMessage", });
    internal_static_Receive_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Receive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Receive_descriptor,
        new java.lang.String[] { "Filter", });
    internal_static_Filter_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Filter_descriptor,
        new java.lang.String[] { "MessageUuids", });
    internal_static_Fetch_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Fetch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Fetch_descriptor,
        new java.lang.String[] { });
    internal_static_Disconnect_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Disconnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Disconnect_descriptor,
        new java.lang.String[] { });
    internal_static_Connect_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Connect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Connect_descriptor,
        new java.lang.String[] { "OwnMrn", "ReconnectToken", });
    internal_static_Notify_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Notify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Notify_descriptor,
        new java.lang.String[] { "MessageMetadata", });
    internal_static_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResponseMessage_descriptor,
        new java.lang.String[] { "ResponseToUuid", "Response", "ReasonText", "MessageMetadata", "MessageContent", "ReconnectToken", });
    internal_static_MessageMetadata_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_MessageMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageMetadata_descriptor,
        new java.lang.String[] { "Uuid", "Header", });
    internal_static_MessageContent_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_MessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageContent_descriptor,
        new java.lang.String[] { "Uuid", "Msg", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
