// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code Notify}
 */
public final class Notify extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Notify)
    NotifyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Notify.class.getName());
  }
  // Use Notify.newBuilder() to construct.
  private Notify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Notify() {
    messageMetadata_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Notify_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Notify_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.Notify.class, net.maritimeconnectivity.mmtp.Notify.Builder.class);
  }

  public static final int MESSAGEMETADATA_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> messageMetadata_;
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  @java.lang.Override
  public java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> getMessageMetadataList() {
    return messageMetadata_;
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
      getMessageMetadataOrBuilderList() {
    return messageMetadata_;
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  @java.lang.Override
  public int getMessageMetadataCount() {
    return messageMetadata_.size();
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MessageMetadata getMessageMetadata(int index) {
    return messageMetadata_.get(index);
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder getMessageMetadataOrBuilder(
      int index) {
    return messageMetadata_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < messageMetadata_.size(); i++) {
      output.writeMessage(1, messageMetadata_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < messageMetadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, messageMetadata_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.Notify)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.Notify other = (net.maritimeconnectivity.mmtp.Notify) obj;

    if (!getMessageMetadataList()
        .equals(other.getMessageMetadataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessageMetadataCount() > 0) {
      hash = (37 * hash) + MESSAGEMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMessageMetadataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.Notify parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.Notify parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Notify parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.Notify prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Notify}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Notify)
      net.maritimeconnectivity.mmtp.NotifyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Notify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Notify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.Notify.class, net.maritimeconnectivity.mmtp.Notify.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.Notify.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (messageMetadataBuilder_ == null) {
        messageMetadata_ = java.util.Collections.emptyList();
      } else {
        messageMetadata_ = null;
        messageMetadataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Notify_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Notify getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Notify build() {
      net.maritimeconnectivity.mmtp.Notify result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Notify buildPartial() {
      net.maritimeconnectivity.mmtp.Notify result = new net.maritimeconnectivity.mmtp.Notify(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(net.maritimeconnectivity.mmtp.Notify result) {
      if (messageMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messageMetadata_ = java.util.Collections.unmodifiableList(messageMetadata_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messageMetadata_ = messageMetadata_;
      } else {
        result.messageMetadata_ = messageMetadataBuilder_.build();
      }
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.Notify result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.Notify) {
        return mergeFrom((net.maritimeconnectivity.mmtp.Notify)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.Notify other) {
      if (other == net.maritimeconnectivity.mmtp.Notify.getDefaultInstance()) return this;
      if (messageMetadataBuilder_ == null) {
        if (!other.messageMetadata_.isEmpty()) {
          if (messageMetadata_.isEmpty()) {
            messageMetadata_ = other.messageMetadata_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessageMetadataIsMutable();
            messageMetadata_.addAll(other.messageMetadata_);
          }
          onChanged();
        }
      } else {
        if (!other.messageMetadata_.isEmpty()) {
          if (messageMetadataBuilder_.isEmpty()) {
            messageMetadataBuilder_.dispose();
            messageMetadataBuilder_ = null;
            messageMetadata_ = other.messageMetadata_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messageMetadataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMessageMetadataFieldBuilder() : null;
          } else {
            messageMetadataBuilder_.addAllMessages(other.messageMetadata_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.maritimeconnectivity.mmtp.MessageMetadata m =
                  input.readMessage(
                      net.maritimeconnectivity.mmtp.MessageMetadata.parser(),
                      extensionRegistry);
              if (messageMetadataBuilder_ == null) {
                ensureMessageMetadataIsMutable();
                messageMetadata_.add(m);
              } else {
                messageMetadataBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> messageMetadata_ =
      java.util.Collections.emptyList();
    private void ensureMessageMetadataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messageMetadata_ = new java.util.ArrayList<net.maritimeconnectivity.mmtp.MessageMetadata>(messageMetadata_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        net.maritimeconnectivity.mmtp.MessageMetadata, net.maritimeconnectivity.mmtp.MessageMetadata.Builder, net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> messageMetadataBuilder_;

    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> getMessageMetadataList() {
      if (messageMetadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messageMetadata_);
      } else {
        return messageMetadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public int getMessageMetadataCount() {
      if (messageMetadataBuilder_ == null) {
        return messageMetadata_.size();
      } else {
        return messageMetadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata getMessageMetadata(int index) {
      if (messageMetadataBuilder_ == null) {
        return messageMetadata_.get(index);
      } else {
        return messageMetadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder setMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata value) {
      if (messageMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageMetadataIsMutable();
        messageMetadata_.set(index, value);
        onChanged();
      } else {
        messageMetadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder setMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata.Builder builderForValue) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageMetadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder addMessageMetadata(net.maritimeconnectivity.mmtp.MessageMetadata value) {
      if (messageMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(value);
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder addMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata value) {
      if (messageMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(index, value);
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder addMessageMetadata(
        net.maritimeconnectivity.mmtp.MessageMetadata.Builder builderForValue) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(builderForValue.build());
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder addMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata.Builder builderForValue) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder addAllMessageMetadata(
        java.lang.Iterable<? extends net.maritimeconnectivity.mmtp.MessageMetadata> values) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageMetadata_);
        onChanged();
      } else {
        messageMetadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder clearMessageMetadata() {
      if (messageMetadataBuilder_ == null) {
        messageMetadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messageMetadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public Builder removeMessageMetadata(int index) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.remove(index);
        onChanged();
      } else {
        messageMetadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata.Builder getMessageMetadataBuilder(
        int index) {
      return getMessageMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder getMessageMetadataOrBuilder(
        int index) {
      if (messageMetadataBuilder_ == null) {
        return messageMetadata_.get(index);  } else {
        return messageMetadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public java.util.List<? extends net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
         getMessageMetadataOrBuilderList() {
      if (messageMetadataBuilder_ != null) {
        return messageMetadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messageMetadata_);
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata.Builder addMessageMetadataBuilder() {
      return getMessageMetadataFieldBuilder().addBuilder(
          net.maritimeconnectivity.mmtp.MessageMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata.Builder addMessageMetadataBuilder(
        int index) {
      return getMessageMetadataFieldBuilder().addBuilder(
          index, net.maritimeconnectivity.mmtp.MessageMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 1;</code>
     */
    public java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata.Builder> 
         getMessageMetadataBuilderList() {
      return getMessageMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        net.maritimeconnectivity.mmtp.MessageMetadata, net.maritimeconnectivity.mmtp.MessageMetadata.Builder, net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
        getMessageMetadataFieldBuilder() {
      if (messageMetadataBuilder_ == null) {
        messageMetadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            net.maritimeconnectivity.mmtp.MessageMetadata, net.maritimeconnectivity.mmtp.MessageMetadata.Builder, net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder>(
                messageMetadata_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messageMetadata_ = null;
      }
      return messageMetadataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Notify)
  }

  // @@protoc_insertion_point(class_scope:Notify)
  private static final net.maritimeconnectivity.mmtp.Notify DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.Notify();
  }

  public static net.maritimeconnectivity.mmtp.Notify getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Notify>
      PARSER = new com.google.protobuf.AbstractParser<Notify>() {
    @java.lang.Override
    public Notify parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Notify> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Notify> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Notify getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

