// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface NotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Notify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> 
      getMessageMetadataList();
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  net.maritimeconnectivity.mmtp.MessageMetadata getMessageMetadata(int index);
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  int getMessageMetadataCount();
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  java.util.List<? extends net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
      getMessageMetadataOrBuilderList();
  /**
   * <code>repeated .MessageMetadata messageMetadata = 1;</code>
   */
  net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder getMessageMetadataOrBuilder(
      int index);
}
