// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code ProtocolMessage}
 */
public final class ProtocolMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ProtocolMessage)
    ProtocolMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ProtocolMessage.class.getName());
  }
  // Use ProtocolMessage.newBuilder() to construct.
  private ProtocolMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtocolMessage() {
    protocolMsgType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ProtocolMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ProtocolMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.ProtocolMessage.class, net.maritimeconnectivity.mmtp.ProtocolMessage.Builder.class);
  }

  private int bodyCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SUBSCRIBEMESSAGE(2),
    UNSUBSCRIBEMESSAGE(3),
    SENDMESSAGE(4),
    RECEIVEMESSAGE(5),
    FETCHMESSAGE(6),
    DISCONNECTMESSAGE(7),
    CONNECTMESSAGE(8),
    NOTIFYMESSAGE(9),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return SUBSCRIBEMESSAGE;
        case 3: return UNSUBSCRIBEMESSAGE;
        case 4: return SENDMESSAGE;
        case 5: return RECEIVEMESSAGE;
        case 6: return FETCHMESSAGE;
        case 7: return DISCONNECTMESSAGE;
        case 8: return CONNECTMESSAGE;
        case 9: return NOTIFYMESSAGE;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int PROTOCOLMSGTYPE_FIELD_NUMBER = 1;
  private int protocolMsgType_ = 0;
  /**
   * <code>.ProtocolMessageType protocolMsgType = 1;</code>
   * @return The enum numeric value on the wire for protocolMsgType.
   */
  @java.lang.Override public int getProtocolMsgTypeValue() {
    return protocolMsgType_;
  }
  /**
   * <code>.ProtocolMessageType protocolMsgType = 1;</code>
   * @return The protocolMsgType.
   */
  @java.lang.Override public net.maritimeconnectivity.mmtp.ProtocolMessageType getProtocolMsgType() {
    net.maritimeconnectivity.mmtp.ProtocolMessageType result = net.maritimeconnectivity.mmtp.ProtocolMessageType.forNumber(protocolMsgType_);
    return result == null ? net.maritimeconnectivity.mmtp.ProtocolMessageType.UNRECOGNIZED : result;
  }

  public static final int SUBSCRIBEMESSAGE_FIELD_NUMBER = 2;
  /**
   * <code>.Subscribe subscribeMessage = 2;</code>
   * @return Whether the subscribeMessage field is set.
   */
  @java.lang.Override
  public boolean hasSubscribeMessage() {
    return bodyCase_ == 2;
  }
  /**
   * <code>.Subscribe subscribeMessage = 2;</code>
   * @return The subscribeMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Subscribe getSubscribeMessage() {
    if (bodyCase_ == 2) {
       return (net.maritimeconnectivity.mmtp.Subscribe) body_;
    }
    return net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
  }
  /**
   * <code>.Subscribe subscribeMessage = 2;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.SubscribeOrBuilder getSubscribeMessageOrBuilder() {
    if (bodyCase_ == 2) {
       return (net.maritimeconnectivity.mmtp.Subscribe) body_;
    }
    return net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
  }

  public static final int UNSUBSCRIBEMESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>.Unsubscribe unsubscribeMessage = 3;</code>
   * @return Whether the unsubscribeMessage field is set.
   */
  @java.lang.Override
  public boolean hasUnsubscribeMessage() {
    return bodyCase_ == 3;
  }
  /**
   * <code>.Unsubscribe unsubscribeMessage = 3;</code>
   * @return The unsubscribeMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Unsubscribe getUnsubscribeMessage() {
    if (bodyCase_ == 3) {
       return (net.maritimeconnectivity.mmtp.Unsubscribe) body_;
    }
    return net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance();
  }
  /**
   * <code>.Unsubscribe unsubscribeMessage = 3;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.UnsubscribeOrBuilder getUnsubscribeMessageOrBuilder() {
    if (bodyCase_ == 3) {
       return (net.maritimeconnectivity.mmtp.Unsubscribe) body_;
    }
    return net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance();
  }

  public static final int SENDMESSAGE_FIELD_NUMBER = 4;
  /**
   * <code>.Send sendMessage = 4;</code>
   * @return Whether the sendMessage field is set.
   */
  @java.lang.Override
  public boolean hasSendMessage() {
    return bodyCase_ == 4;
  }
  /**
   * <code>.Send sendMessage = 4;</code>
   * @return The sendMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Send getSendMessage() {
    if (bodyCase_ == 4) {
       return (net.maritimeconnectivity.mmtp.Send) body_;
    }
    return net.maritimeconnectivity.mmtp.Send.getDefaultInstance();
  }
  /**
   * <code>.Send sendMessage = 4;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.SendOrBuilder getSendMessageOrBuilder() {
    if (bodyCase_ == 4) {
       return (net.maritimeconnectivity.mmtp.Send) body_;
    }
    return net.maritimeconnectivity.mmtp.Send.getDefaultInstance();
  }

  public static final int RECEIVEMESSAGE_FIELD_NUMBER = 5;
  /**
   * <code>.Receive receiveMessage = 5;</code>
   * @return Whether the receiveMessage field is set.
   */
  @java.lang.Override
  public boolean hasReceiveMessage() {
    return bodyCase_ == 5;
  }
  /**
   * <code>.Receive receiveMessage = 5;</code>
   * @return The receiveMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Receive getReceiveMessage() {
    if (bodyCase_ == 5) {
       return (net.maritimeconnectivity.mmtp.Receive) body_;
    }
    return net.maritimeconnectivity.mmtp.Receive.getDefaultInstance();
  }
  /**
   * <code>.Receive receiveMessage = 5;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ReceiveOrBuilder getReceiveMessageOrBuilder() {
    if (bodyCase_ == 5) {
       return (net.maritimeconnectivity.mmtp.Receive) body_;
    }
    return net.maritimeconnectivity.mmtp.Receive.getDefaultInstance();
  }

  public static final int FETCHMESSAGE_FIELD_NUMBER = 6;
  /**
   * <code>.Fetch fetchMessage = 6;</code>
   * @return Whether the fetchMessage field is set.
   */
  @java.lang.Override
  public boolean hasFetchMessage() {
    return bodyCase_ == 6;
  }
  /**
   * <code>.Fetch fetchMessage = 6;</code>
   * @return The fetchMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Fetch getFetchMessage() {
    if (bodyCase_ == 6) {
       return (net.maritimeconnectivity.mmtp.Fetch) body_;
    }
    return net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance();
  }
  /**
   * <code>.Fetch fetchMessage = 6;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.FetchOrBuilder getFetchMessageOrBuilder() {
    if (bodyCase_ == 6) {
       return (net.maritimeconnectivity.mmtp.Fetch) body_;
    }
    return net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance();
  }

  public static final int DISCONNECTMESSAGE_FIELD_NUMBER = 7;
  /**
   * <code>.Disconnect disconnectMessage = 7;</code>
   * @return Whether the disconnectMessage field is set.
   */
  @java.lang.Override
  public boolean hasDisconnectMessage() {
    return bodyCase_ == 7;
  }
  /**
   * <code>.Disconnect disconnectMessage = 7;</code>
   * @return The disconnectMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Disconnect getDisconnectMessage() {
    if (bodyCase_ == 7) {
       return (net.maritimeconnectivity.mmtp.Disconnect) body_;
    }
    return net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance();
  }
  /**
   * <code>.Disconnect disconnectMessage = 7;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.DisconnectOrBuilder getDisconnectMessageOrBuilder() {
    if (bodyCase_ == 7) {
       return (net.maritimeconnectivity.mmtp.Disconnect) body_;
    }
    return net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance();
  }

  public static final int CONNECTMESSAGE_FIELD_NUMBER = 8;
  /**
   * <code>.Connect connectMessage = 8;</code>
   * @return Whether the connectMessage field is set.
   */
  @java.lang.Override
  public boolean hasConnectMessage() {
    return bodyCase_ == 8;
  }
  /**
   * <code>.Connect connectMessage = 8;</code>
   * @return The connectMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Connect getConnectMessage() {
    if (bodyCase_ == 8) {
       return (net.maritimeconnectivity.mmtp.Connect) body_;
    }
    return net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
  }
  /**
   * <code>.Connect connectMessage = 8;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ConnectOrBuilder getConnectMessageOrBuilder() {
    if (bodyCase_ == 8) {
       return (net.maritimeconnectivity.mmtp.Connect) body_;
    }
    return net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
  }

  public static final int NOTIFYMESSAGE_FIELD_NUMBER = 9;
  /**
   * <code>.Notify notifyMessage = 9;</code>
   * @return Whether the notifyMessage field is set.
   */
  @java.lang.Override
  public boolean hasNotifyMessage() {
    return bodyCase_ == 9;
  }
  /**
   * <code>.Notify notifyMessage = 9;</code>
   * @return The notifyMessage.
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Notify getNotifyMessage() {
    if (bodyCase_ == 9) {
       return (net.maritimeconnectivity.mmtp.Notify) body_;
    }
    return net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
  }
  /**
   * <code>.Notify notifyMessage = 9;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.NotifyOrBuilder getNotifyMessageOrBuilder() {
    if (bodyCase_ == 9) {
       return (net.maritimeconnectivity.mmtp.Notify) body_;
    }
    return net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (protocolMsgType_ != net.maritimeconnectivity.mmtp.ProtocolMessageType.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, protocolMsgType_);
    }
    if (bodyCase_ == 2) {
      output.writeMessage(2, (net.maritimeconnectivity.mmtp.Subscribe) body_);
    }
    if (bodyCase_ == 3) {
      output.writeMessage(3, (net.maritimeconnectivity.mmtp.Unsubscribe) body_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (net.maritimeconnectivity.mmtp.Send) body_);
    }
    if (bodyCase_ == 5) {
      output.writeMessage(5, (net.maritimeconnectivity.mmtp.Receive) body_);
    }
    if (bodyCase_ == 6) {
      output.writeMessage(6, (net.maritimeconnectivity.mmtp.Fetch) body_);
    }
    if (bodyCase_ == 7) {
      output.writeMessage(7, (net.maritimeconnectivity.mmtp.Disconnect) body_);
    }
    if (bodyCase_ == 8) {
      output.writeMessage(8, (net.maritimeconnectivity.mmtp.Connect) body_);
    }
    if (bodyCase_ == 9) {
      output.writeMessage(9, (net.maritimeconnectivity.mmtp.Notify) body_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (protocolMsgType_ != net.maritimeconnectivity.mmtp.ProtocolMessageType.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, protocolMsgType_);
    }
    if (bodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (net.maritimeconnectivity.mmtp.Subscribe) body_);
    }
    if (bodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (net.maritimeconnectivity.mmtp.Unsubscribe) body_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (net.maritimeconnectivity.mmtp.Send) body_);
    }
    if (bodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (net.maritimeconnectivity.mmtp.Receive) body_);
    }
    if (bodyCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (net.maritimeconnectivity.mmtp.Fetch) body_);
    }
    if (bodyCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (net.maritimeconnectivity.mmtp.Disconnect) body_);
    }
    if (bodyCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (net.maritimeconnectivity.mmtp.Connect) body_);
    }
    if (bodyCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (net.maritimeconnectivity.mmtp.Notify) body_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.ProtocolMessage)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.ProtocolMessage other = (net.maritimeconnectivity.mmtp.ProtocolMessage) obj;

    if (protocolMsgType_ != other.protocolMsgType_) return false;
    if (!getBodyCase().equals(other.getBodyCase())) return false;
    switch (bodyCase_) {
      case 2:
        if (!getSubscribeMessage()
            .equals(other.getSubscribeMessage())) return false;
        break;
      case 3:
        if (!getUnsubscribeMessage()
            .equals(other.getUnsubscribeMessage())) return false;
        break;
      case 4:
        if (!getSendMessage()
            .equals(other.getSendMessage())) return false;
        break;
      case 5:
        if (!getReceiveMessage()
            .equals(other.getReceiveMessage())) return false;
        break;
      case 6:
        if (!getFetchMessage()
            .equals(other.getFetchMessage())) return false;
        break;
      case 7:
        if (!getDisconnectMessage()
            .equals(other.getDisconnectMessage())) return false;
        break;
      case 8:
        if (!getConnectMessage()
            .equals(other.getConnectMessage())) return false;
        break;
      case 9:
        if (!getNotifyMessage()
            .equals(other.getNotifyMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTOCOLMSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + protocolMsgType_;
    switch (bodyCase_) {
      case 2:
        hash = (37 * hash) + SUBSCRIBEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSubscribeMessage().hashCode();
        break;
      case 3:
        hash = (37 * hash) + UNSUBSCRIBEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getUnsubscribeMessage().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SENDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSendMessage().hashCode();
        break;
      case 5:
        hash = (37 * hash) + RECEIVEMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getReceiveMessage().hashCode();
        break;
      case 6:
        hash = (37 * hash) + FETCHMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getFetchMessage().hashCode();
        break;
      case 7:
        hash = (37 * hash) + DISCONNECTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getDisconnectMessage().hashCode();
        break;
      case 8:
        hash = (37 * hash) + CONNECTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getConnectMessage().hashCode();
        break;
      case 9:
        hash = (37 * hash) + NOTIFYMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getNotifyMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.ProtocolMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.ProtocolMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProtocolMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtocolMessage)
      net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ProtocolMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ProtocolMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.ProtocolMessage.class, net.maritimeconnectivity.mmtp.ProtocolMessage.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.ProtocolMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      protocolMsgType_ = 0;
      if (subscribeMessageBuilder_ != null) {
        subscribeMessageBuilder_.clear();
      }
      if (unsubscribeMessageBuilder_ != null) {
        unsubscribeMessageBuilder_.clear();
      }
      if (sendMessageBuilder_ != null) {
        sendMessageBuilder_.clear();
      }
      if (receiveMessageBuilder_ != null) {
        receiveMessageBuilder_.clear();
      }
      if (fetchMessageBuilder_ != null) {
        fetchMessageBuilder_.clear();
      }
      if (disconnectMessageBuilder_ != null) {
        disconnectMessageBuilder_.clear();
      }
      if (connectMessageBuilder_ != null) {
        connectMessageBuilder_.clear();
      }
      if (notifyMessageBuilder_ != null) {
        notifyMessageBuilder_.clear();
      }
      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ProtocolMessage_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ProtocolMessage getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ProtocolMessage build() {
      net.maritimeconnectivity.mmtp.ProtocolMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ProtocolMessage buildPartial() {
      net.maritimeconnectivity.mmtp.ProtocolMessage result = new net.maritimeconnectivity.mmtp.ProtocolMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.ProtocolMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.protocolMsgType_ = protocolMsgType_;
      }
    }

    private void buildPartialOneofs(net.maritimeconnectivity.mmtp.ProtocolMessage result) {
      result.bodyCase_ = bodyCase_;
      result.body_ = this.body_;
      if (bodyCase_ == 2 &&
          subscribeMessageBuilder_ != null) {
        result.body_ = subscribeMessageBuilder_.build();
      }
      if (bodyCase_ == 3 &&
          unsubscribeMessageBuilder_ != null) {
        result.body_ = unsubscribeMessageBuilder_.build();
      }
      if (bodyCase_ == 4 &&
          sendMessageBuilder_ != null) {
        result.body_ = sendMessageBuilder_.build();
      }
      if (bodyCase_ == 5 &&
          receiveMessageBuilder_ != null) {
        result.body_ = receiveMessageBuilder_.build();
      }
      if (bodyCase_ == 6 &&
          fetchMessageBuilder_ != null) {
        result.body_ = fetchMessageBuilder_.build();
      }
      if (bodyCase_ == 7 &&
          disconnectMessageBuilder_ != null) {
        result.body_ = disconnectMessageBuilder_.build();
      }
      if (bodyCase_ == 8 &&
          connectMessageBuilder_ != null) {
        result.body_ = connectMessageBuilder_.build();
      }
      if (bodyCase_ == 9 &&
          notifyMessageBuilder_ != null) {
        result.body_ = notifyMessageBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.ProtocolMessage) {
        return mergeFrom((net.maritimeconnectivity.mmtp.ProtocolMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.ProtocolMessage other) {
      if (other == net.maritimeconnectivity.mmtp.ProtocolMessage.getDefaultInstance()) return this;
      if (other.protocolMsgType_ != 0) {
        setProtocolMsgTypeValue(other.getProtocolMsgTypeValue());
      }
      switch (other.getBodyCase()) {
        case SUBSCRIBEMESSAGE: {
          mergeSubscribeMessage(other.getSubscribeMessage());
          break;
        }
        case UNSUBSCRIBEMESSAGE: {
          mergeUnsubscribeMessage(other.getUnsubscribeMessage());
          break;
        }
        case SENDMESSAGE: {
          mergeSendMessage(other.getSendMessage());
          break;
        }
        case RECEIVEMESSAGE: {
          mergeReceiveMessage(other.getReceiveMessage());
          break;
        }
        case FETCHMESSAGE: {
          mergeFetchMessage(other.getFetchMessage());
          break;
        }
        case DISCONNECTMESSAGE: {
          mergeDisconnectMessage(other.getDisconnectMessage());
          break;
        }
        case CONNECTMESSAGE: {
          mergeConnectMessage(other.getConnectMessage());
          break;
        }
        case NOTIFYMESSAGE: {
          mergeNotifyMessage(other.getNotifyMessage());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              protocolMsgType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getSubscribeMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getUnsubscribeMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSendMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getReceiveMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getFetchMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getDisconnectMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getConnectMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getNotifyMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 9;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int protocolMsgType_ = 0;
    /**
     * <code>.ProtocolMessageType protocolMsgType = 1;</code>
     * @return The enum numeric value on the wire for protocolMsgType.
     */
    @java.lang.Override public int getProtocolMsgTypeValue() {
      return protocolMsgType_;
    }
    /**
     * <code>.ProtocolMessageType protocolMsgType = 1;</code>
     * @param value The enum numeric value on the wire for protocolMsgType to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolMsgTypeValue(int value) {
      protocolMsgType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ProtocolMessageType protocolMsgType = 1;</code>
     * @return The protocolMsgType.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ProtocolMessageType getProtocolMsgType() {
      net.maritimeconnectivity.mmtp.ProtocolMessageType result = net.maritimeconnectivity.mmtp.ProtocolMessageType.forNumber(protocolMsgType_);
      return result == null ? net.maritimeconnectivity.mmtp.ProtocolMessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ProtocolMessageType protocolMsgType = 1;</code>
     * @param value The protocolMsgType to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolMsgType(net.maritimeconnectivity.mmtp.ProtocolMessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      protocolMsgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ProtocolMessageType protocolMsgType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolMsgType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      protocolMsgType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Subscribe, net.maritimeconnectivity.mmtp.Subscribe.Builder, net.maritimeconnectivity.mmtp.SubscribeOrBuilder> subscribeMessageBuilder_;
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     * @return Whether the subscribeMessage field is set.
     */
    @java.lang.Override
    public boolean hasSubscribeMessage() {
      return bodyCase_ == 2;
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     * @return The subscribeMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Subscribe getSubscribeMessage() {
      if (subscribeMessageBuilder_ == null) {
        if (bodyCase_ == 2) {
          return (net.maritimeconnectivity.mmtp.Subscribe) body_;
        }
        return net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
      } else {
        if (bodyCase_ == 2) {
          return subscribeMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
      }
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    public Builder setSubscribeMessage(net.maritimeconnectivity.mmtp.Subscribe value) {
      if (subscribeMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        subscribeMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    public Builder setSubscribeMessage(
        net.maritimeconnectivity.mmtp.Subscribe.Builder builderForValue) {
      if (subscribeMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        subscribeMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    public Builder mergeSubscribeMessage(net.maritimeconnectivity.mmtp.Subscribe value) {
      if (subscribeMessageBuilder_ == null) {
        if (bodyCase_ == 2 &&
            body_ != net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Subscribe.newBuilder((net.maritimeconnectivity.mmtp.Subscribe) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 2) {
          subscribeMessageBuilder_.mergeFrom(value);
        } else {
          subscribeMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    public Builder clearSubscribeMessage() {
      if (subscribeMessageBuilder_ == null) {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
        }
        subscribeMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    public net.maritimeconnectivity.mmtp.Subscribe.Builder getSubscribeMessageBuilder() {
      return getSubscribeMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.SubscribeOrBuilder getSubscribeMessageOrBuilder() {
      if ((bodyCase_ == 2) && (subscribeMessageBuilder_ != null)) {
        return subscribeMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 2) {
          return (net.maritimeconnectivity.mmtp.Subscribe) body_;
        }
        return net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
      }
    }
    /**
     * <code>.Subscribe subscribeMessage = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Subscribe, net.maritimeconnectivity.mmtp.Subscribe.Builder, net.maritimeconnectivity.mmtp.SubscribeOrBuilder> 
        getSubscribeMessageFieldBuilder() {
      if (subscribeMessageBuilder_ == null) {
        if (!(bodyCase_ == 2)) {
          body_ = net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
        }
        subscribeMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Subscribe, net.maritimeconnectivity.mmtp.Subscribe.Builder, net.maritimeconnectivity.mmtp.SubscribeOrBuilder>(
                (net.maritimeconnectivity.mmtp.Subscribe) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 2;
      onChanged();
      return subscribeMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Unsubscribe, net.maritimeconnectivity.mmtp.Unsubscribe.Builder, net.maritimeconnectivity.mmtp.UnsubscribeOrBuilder> unsubscribeMessageBuilder_;
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     * @return Whether the unsubscribeMessage field is set.
     */
    @java.lang.Override
    public boolean hasUnsubscribeMessage() {
      return bodyCase_ == 3;
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     * @return The unsubscribeMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Unsubscribe getUnsubscribeMessage() {
      if (unsubscribeMessageBuilder_ == null) {
        if (bodyCase_ == 3) {
          return (net.maritimeconnectivity.mmtp.Unsubscribe) body_;
        }
        return net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance();
      } else {
        if (bodyCase_ == 3) {
          return unsubscribeMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance();
      }
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    public Builder setUnsubscribeMessage(net.maritimeconnectivity.mmtp.Unsubscribe value) {
      if (unsubscribeMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        unsubscribeMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    public Builder setUnsubscribeMessage(
        net.maritimeconnectivity.mmtp.Unsubscribe.Builder builderForValue) {
      if (unsubscribeMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        unsubscribeMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    public Builder mergeUnsubscribeMessage(net.maritimeconnectivity.mmtp.Unsubscribe value) {
      if (unsubscribeMessageBuilder_ == null) {
        if (bodyCase_ == 3 &&
            body_ != net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Unsubscribe.newBuilder((net.maritimeconnectivity.mmtp.Unsubscribe) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 3) {
          unsubscribeMessageBuilder_.mergeFrom(value);
        } else {
          unsubscribeMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    public Builder clearUnsubscribeMessage() {
      if (unsubscribeMessageBuilder_ == null) {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
        }
        unsubscribeMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    public net.maritimeconnectivity.mmtp.Unsubscribe.Builder getUnsubscribeMessageBuilder() {
      return getUnsubscribeMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.UnsubscribeOrBuilder getUnsubscribeMessageOrBuilder() {
      if ((bodyCase_ == 3) && (unsubscribeMessageBuilder_ != null)) {
        return unsubscribeMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 3) {
          return (net.maritimeconnectivity.mmtp.Unsubscribe) body_;
        }
        return net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance();
      }
    }
    /**
     * <code>.Unsubscribe unsubscribeMessage = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Unsubscribe, net.maritimeconnectivity.mmtp.Unsubscribe.Builder, net.maritimeconnectivity.mmtp.UnsubscribeOrBuilder> 
        getUnsubscribeMessageFieldBuilder() {
      if (unsubscribeMessageBuilder_ == null) {
        if (!(bodyCase_ == 3)) {
          body_ = net.maritimeconnectivity.mmtp.Unsubscribe.getDefaultInstance();
        }
        unsubscribeMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Unsubscribe, net.maritimeconnectivity.mmtp.Unsubscribe.Builder, net.maritimeconnectivity.mmtp.UnsubscribeOrBuilder>(
                (net.maritimeconnectivity.mmtp.Unsubscribe) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 3;
      onChanged();
      return unsubscribeMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Send, net.maritimeconnectivity.mmtp.Send.Builder, net.maritimeconnectivity.mmtp.SendOrBuilder> sendMessageBuilder_;
    /**
     * <code>.Send sendMessage = 4;</code>
     * @return Whether the sendMessage field is set.
     */
    @java.lang.Override
    public boolean hasSendMessage() {
      return bodyCase_ == 4;
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     * @return The sendMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Send getSendMessage() {
      if (sendMessageBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (net.maritimeconnectivity.mmtp.Send) body_;
        }
        return net.maritimeconnectivity.mmtp.Send.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return sendMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Send.getDefaultInstance();
      }
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    public Builder setSendMessage(net.maritimeconnectivity.mmtp.Send value) {
      if (sendMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        sendMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    public Builder setSendMessage(
        net.maritimeconnectivity.mmtp.Send.Builder builderForValue) {
      if (sendMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        sendMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    public Builder mergeSendMessage(net.maritimeconnectivity.mmtp.Send value) {
      if (sendMessageBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != net.maritimeconnectivity.mmtp.Send.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Send.newBuilder((net.maritimeconnectivity.mmtp.Send) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          sendMessageBuilder_.mergeFrom(value);
        } else {
          sendMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    public Builder clearSendMessage() {
      if (sendMessageBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        sendMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.Send.Builder getSendMessageBuilder() {
      return getSendMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.SendOrBuilder getSendMessageOrBuilder() {
      if ((bodyCase_ == 4) && (sendMessageBuilder_ != null)) {
        return sendMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (net.maritimeconnectivity.mmtp.Send) body_;
        }
        return net.maritimeconnectivity.mmtp.Send.getDefaultInstance();
      }
    }
    /**
     * <code>.Send sendMessage = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Send, net.maritimeconnectivity.mmtp.Send.Builder, net.maritimeconnectivity.mmtp.SendOrBuilder> 
        getSendMessageFieldBuilder() {
      if (sendMessageBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = net.maritimeconnectivity.mmtp.Send.getDefaultInstance();
        }
        sendMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Send, net.maritimeconnectivity.mmtp.Send.Builder, net.maritimeconnectivity.mmtp.SendOrBuilder>(
                (net.maritimeconnectivity.mmtp.Send) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();
      return sendMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Receive, net.maritimeconnectivity.mmtp.Receive.Builder, net.maritimeconnectivity.mmtp.ReceiveOrBuilder> receiveMessageBuilder_;
    /**
     * <code>.Receive receiveMessage = 5;</code>
     * @return Whether the receiveMessage field is set.
     */
    @java.lang.Override
    public boolean hasReceiveMessage() {
      return bodyCase_ == 5;
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     * @return The receiveMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Receive getReceiveMessage() {
      if (receiveMessageBuilder_ == null) {
        if (bodyCase_ == 5) {
          return (net.maritimeconnectivity.mmtp.Receive) body_;
        }
        return net.maritimeconnectivity.mmtp.Receive.getDefaultInstance();
      } else {
        if (bodyCase_ == 5) {
          return receiveMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Receive.getDefaultInstance();
      }
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    public Builder setReceiveMessage(net.maritimeconnectivity.mmtp.Receive value) {
      if (receiveMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        receiveMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    public Builder setReceiveMessage(
        net.maritimeconnectivity.mmtp.Receive.Builder builderForValue) {
      if (receiveMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        receiveMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    public Builder mergeReceiveMessage(net.maritimeconnectivity.mmtp.Receive value) {
      if (receiveMessageBuilder_ == null) {
        if (bodyCase_ == 5 &&
            body_ != net.maritimeconnectivity.mmtp.Receive.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Receive.newBuilder((net.maritimeconnectivity.mmtp.Receive) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 5) {
          receiveMessageBuilder_.mergeFrom(value);
        } else {
          receiveMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    public Builder clearReceiveMessage() {
      if (receiveMessageBuilder_ == null) {
        if (bodyCase_ == 5) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 5) {
          bodyCase_ = 0;
          body_ = null;
        }
        receiveMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    public net.maritimeconnectivity.mmtp.Receive.Builder getReceiveMessageBuilder() {
      return getReceiveMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ReceiveOrBuilder getReceiveMessageOrBuilder() {
      if ((bodyCase_ == 5) && (receiveMessageBuilder_ != null)) {
        return receiveMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 5) {
          return (net.maritimeconnectivity.mmtp.Receive) body_;
        }
        return net.maritimeconnectivity.mmtp.Receive.getDefaultInstance();
      }
    }
    /**
     * <code>.Receive receiveMessage = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Receive, net.maritimeconnectivity.mmtp.Receive.Builder, net.maritimeconnectivity.mmtp.ReceiveOrBuilder> 
        getReceiveMessageFieldBuilder() {
      if (receiveMessageBuilder_ == null) {
        if (!(bodyCase_ == 5)) {
          body_ = net.maritimeconnectivity.mmtp.Receive.getDefaultInstance();
        }
        receiveMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Receive, net.maritimeconnectivity.mmtp.Receive.Builder, net.maritimeconnectivity.mmtp.ReceiveOrBuilder>(
                (net.maritimeconnectivity.mmtp.Receive) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 5;
      onChanged();
      return receiveMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Fetch, net.maritimeconnectivity.mmtp.Fetch.Builder, net.maritimeconnectivity.mmtp.FetchOrBuilder> fetchMessageBuilder_;
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     * @return Whether the fetchMessage field is set.
     */
    @java.lang.Override
    public boolean hasFetchMessage() {
      return bodyCase_ == 6;
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     * @return The fetchMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Fetch getFetchMessage() {
      if (fetchMessageBuilder_ == null) {
        if (bodyCase_ == 6) {
          return (net.maritimeconnectivity.mmtp.Fetch) body_;
        }
        return net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance();
      } else {
        if (bodyCase_ == 6) {
          return fetchMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance();
      }
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    public Builder setFetchMessage(net.maritimeconnectivity.mmtp.Fetch value) {
      if (fetchMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        fetchMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 6;
      return this;
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    public Builder setFetchMessage(
        net.maritimeconnectivity.mmtp.Fetch.Builder builderForValue) {
      if (fetchMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        fetchMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 6;
      return this;
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    public Builder mergeFetchMessage(net.maritimeconnectivity.mmtp.Fetch value) {
      if (fetchMessageBuilder_ == null) {
        if (bodyCase_ == 6 &&
            body_ != net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Fetch.newBuilder((net.maritimeconnectivity.mmtp.Fetch) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 6) {
          fetchMessageBuilder_.mergeFrom(value);
        } else {
          fetchMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 6;
      return this;
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    public Builder clearFetchMessage() {
      if (fetchMessageBuilder_ == null) {
        if (bodyCase_ == 6) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 6) {
          bodyCase_ = 0;
          body_ = null;
        }
        fetchMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    public net.maritimeconnectivity.mmtp.Fetch.Builder getFetchMessageBuilder() {
      return getFetchMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.FetchOrBuilder getFetchMessageOrBuilder() {
      if ((bodyCase_ == 6) && (fetchMessageBuilder_ != null)) {
        return fetchMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 6) {
          return (net.maritimeconnectivity.mmtp.Fetch) body_;
        }
        return net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance();
      }
    }
    /**
     * <code>.Fetch fetchMessage = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Fetch, net.maritimeconnectivity.mmtp.Fetch.Builder, net.maritimeconnectivity.mmtp.FetchOrBuilder> 
        getFetchMessageFieldBuilder() {
      if (fetchMessageBuilder_ == null) {
        if (!(bodyCase_ == 6)) {
          body_ = net.maritimeconnectivity.mmtp.Fetch.getDefaultInstance();
        }
        fetchMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Fetch, net.maritimeconnectivity.mmtp.Fetch.Builder, net.maritimeconnectivity.mmtp.FetchOrBuilder>(
                (net.maritimeconnectivity.mmtp.Fetch) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 6;
      onChanged();
      return fetchMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Disconnect, net.maritimeconnectivity.mmtp.Disconnect.Builder, net.maritimeconnectivity.mmtp.DisconnectOrBuilder> disconnectMessageBuilder_;
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     * @return Whether the disconnectMessage field is set.
     */
    @java.lang.Override
    public boolean hasDisconnectMessage() {
      return bodyCase_ == 7;
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     * @return The disconnectMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Disconnect getDisconnectMessage() {
      if (disconnectMessageBuilder_ == null) {
        if (bodyCase_ == 7) {
          return (net.maritimeconnectivity.mmtp.Disconnect) body_;
        }
        return net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance();
      } else {
        if (bodyCase_ == 7) {
          return disconnectMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance();
      }
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    public Builder setDisconnectMessage(net.maritimeconnectivity.mmtp.Disconnect value) {
      if (disconnectMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        disconnectMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 7;
      return this;
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    public Builder setDisconnectMessage(
        net.maritimeconnectivity.mmtp.Disconnect.Builder builderForValue) {
      if (disconnectMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        disconnectMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 7;
      return this;
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    public Builder mergeDisconnectMessage(net.maritimeconnectivity.mmtp.Disconnect value) {
      if (disconnectMessageBuilder_ == null) {
        if (bodyCase_ == 7 &&
            body_ != net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Disconnect.newBuilder((net.maritimeconnectivity.mmtp.Disconnect) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 7) {
          disconnectMessageBuilder_.mergeFrom(value);
        } else {
          disconnectMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 7;
      return this;
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    public Builder clearDisconnectMessage() {
      if (disconnectMessageBuilder_ == null) {
        if (bodyCase_ == 7) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 7) {
          bodyCase_ = 0;
          body_ = null;
        }
        disconnectMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    public net.maritimeconnectivity.mmtp.Disconnect.Builder getDisconnectMessageBuilder() {
      return getDisconnectMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.DisconnectOrBuilder getDisconnectMessageOrBuilder() {
      if ((bodyCase_ == 7) && (disconnectMessageBuilder_ != null)) {
        return disconnectMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 7) {
          return (net.maritimeconnectivity.mmtp.Disconnect) body_;
        }
        return net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance();
      }
    }
    /**
     * <code>.Disconnect disconnectMessage = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Disconnect, net.maritimeconnectivity.mmtp.Disconnect.Builder, net.maritimeconnectivity.mmtp.DisconnectOrBuilder> 
        getDisconnectMessageFieldBuilder() {
      if (disconnectMessageBuilder_ == null) {
        if (!(bodyCase_ == 7)) {
          body_ = net.maritimeconnectivity.mmtp.Disconnect.getDefaultInstance();
        }
        disconnectMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Disconnect, net.maritimeconnectivity.mmtp.Disconnect.Builder, net.maritimeconnectivity.mmtp.DisconnectOrBuilder>(
                (net.maritimeconnectivity.mmtp.Disconnect) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 7;
      onChanged();
      return disconnectMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Connect, net.maritimeconnectivity.mmtp.Connect.Builder, net.maritimeconnectivity.mmtp.ConnectOrBuilder> connectMessageBuilder_;
    /**
     * <code>.Connect connectMessage = 8;</code>
     * @return Whether the connectMessage field is set.
     */
    @java.lang.Override
    public boolean hasConnectMessage() {
      return bodyCase_ == 8;
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     * @return The connectMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Connect getConnectMessage() {
      if (connectMessageBuilder_ == null) {
        if (bodyCase_ == 8) {
          return (net.maritimeconnectivity.mmtp.Connect) body_;
        }
        return net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
      } else {
        if (bodyCase_ == 8) {
          return connectMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
      }
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    public Builder setConnectMessage(net.maritimeconnectivity.mmtp.Connect value) {
      if (connectMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        connectMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 8;
      return this;
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    public Builder setConnectMessage(
        net.maritimeconnectivity.mmtp.Connect.Builder builderForValue) {
      if (connectMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        connectMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 8;
      return this;
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    public Builder mergeConnectMessage(net.maritimeconnectivity.mmtp.Connect value) {
      if (connectMessageBuilder_ == null) {
        if (bodyCase_ == 8 &&
            body_ != net.maritimeconnectivity.mmtp.Connect.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Connect.newBuilder((net.maritimeconnectivity.mmtp.Connect) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 8) {
          connectMessageBuilder_.mergeFrom(value);
        } else {
          connectMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 8;
      return this;
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    public Builder clearConnectMessage() {
      if (connectMessageBuilder_ == null) {
        if (bodyCase_ == 8) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 8) {
          bodyCase_ = 0;
          body_ = null;
        }
        connectMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    public net.maritimeconnectivity.mmtp.Connect.Builder getConnectMessageBuilder() {
      return getConnectMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ConnectOrBuilder getConnectMessageOrBuilder() {
      if ((bodyCase_ == 8) && (connectMessageBuilder_ != null)) {
        return connectMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 8) {
          return (net.maritimeconnectivity.mmtp.Connect) body_;
        }
        return net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
      }
    }
    /**
     * <code>.Connect connectMessage = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Connect, net.maritimeconnectivity.mmtp.Connect.Builder, net.maritimeconnectivity.mmtp.ConnectOrBuilder> 
        getConnectMessageFieldBuilder() {
      if (connectMessageBuilder_ == null) {
        if (!(bodyCase_ == 8)) {
          body_ = net.maritimeconnectivity.mmtp.Connect.getDefaultInstance();
        }
        connectMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Connect, net.maritimeconnectivity.mmtp.Connect.Builder, net.maritimeconnectivity.mmtp.ConnectOrBuilder>(
                (net.maritimeconnectivity.mmtp.Connect) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 8;
      onChanged();
      return connectMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Notify, net.maritimeconnectivity.mmtp.Notify.Builder, net.maritimeconnectivity.mmtp.NotifyOrBuilder> notifyMessageBuilder_;
    /**
     * <code>.Notify notifyMessage = 9;</code>
     * @return Whether the notifyMessage field is set.
     */
    @java.lang.Override
    public boolean hasNotifyMessage() {
      return bodyCase_ == 9;
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     * @return The notifyMessage.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Notify getNotifyMessage() {
      if (notifyMessageBuilder_ == null) {
        if (bodyCase_ == 9) {
          return (net.maritimeconnectivity.mmtp.Notify) body_;
        }
        return net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
      } else {
        if (bodyCase_ == 9) {
          return notifyMessageBuilder_.getMessage();
        }
        return net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
      }
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    public Builder setNotifyMessage(net.maritimeconnectivity.mmtp.Notify value) {
      if (notifyMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        notifyMessageBuilder_.setMessage(value);
      }
      bodyCase_ = 9;
      return this;
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    public Builder setNotifyMessage(
        net.maritimeconnectivity.mmtp.Notify.Builder builderForValue) {
      if (notifyMessageBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        notifyMessageBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 9;
      return this;
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    public Builder mergeNotifyMessage(net.maritimeconnectivity.mmtp.Notify value) {
      if (notifyMessageBuilder_ == null) {
        if (bodyCase_ == 9 &&
            body_ != net.maritimeconnectivity.mmtp.Notify.getDefaultInstance()) {
          body_ = net.maritimeconnectivity.mmtp.Notify.newBuilder((net.maritimeconnectivity.mmtp.Notify) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 9) {
          notifyMessageBuilder_.mergeFrom(value);
        } else {
          notifyMessageBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 9;
      return this;
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    public Builder clearNotifyMessage() {
      if (notifyMessageBuilder_ == null) {
        if (bodyCase_ == 9) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 9) {
          bodyCase_ = 0;
          body_ = null;
        }
        notifyMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    public net.maritimeconnectivity.mmtp.Notify.Builder getNotifyMessageBuilder() {
      return getNotifyMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.NotifyOrBuilder getNotifyMessageOrBuilder() {
      if ((bodyCase_ == 9) && (notifyMessageBuilder_ != null)) {
        return notifyMessageBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 9) {
          return (net.maritimeconnectivity.mmtp.Notify) body_;
        }
        return net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
      }
    }
    /**
     * <code>.Notify notifyMessage = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.maritimeconnectivity.mmtp.Notify, net.maritimeconnectivity.mmtp.Notify.Builder, net.maritimeconnectivity.mmtp.NotifyOrBuilder> 
        getNotifyMessageFieldBuilder() {
      if (notifyMessageBuilder_ == null) {
        if (!(bodyCase_ == 9)) {
          body_ = net.maritimeconnectivity.mmtp.Notify.getDefaultInstance();
        }
        notifyMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.maritimeconnectivity.mmtp.Notify, net.maritimeconnectivity.mmtp.Notify.Builder, net.maritimeconnectivity.mmtp.NotifyOrBuilder>(
                (net.maritimeconnectivity.mmtp.Notify) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 9;
      onChanged();
      return notifyMessageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ProtocolMessage)
  }

  // @@protoc_insertion_point(class_scope:ProtocolMessage)
  private static final net.maritimeconnectivity.mmtp.ProtocolMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.ProtocolMessage();
  }

  public static net.maritimeconnectivity.mmtp.ProtocolMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtocolMessage>
      PARSER = new com.google.protobuf.AbstractParser<ProtocolMessage>() {
    @java.lang.Override
    public ProtocolMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProtocolMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtocolMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ProtocolMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

