// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface ProtocolMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtocolMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ProtocolMessageType protocolMsgType = 1;</code>
   * @return The enum numeric value on the wire for protocolMsgType.
   */
  int getProtocolMsgTypeValue();
  /**
   * <code>.ProtocolMessageType protocolMsgType = 1;</code>
   * @return The protocolMsgType.
   */
  net.maritimeconnectivity.mmtp.ProtocolMessageType getProtocolMsgType();

  /**
   * <code>.Subscribe subscribeMessage = 2;</code>
   * @return Whether the subscribeMessage field is set.
   */
  boolean hasSubscribeMessage();
  /**
   * <code>.Subscribe subscribeMessage = 2;</code>
   * @return The subscribeMessage.
   */
  net.maritimeconnectivity.mmtp.Subscribe getSubscribeMessage();
  /**
   * <code>.Subscribe subscribeMessage = 2;</code>
   */
  net.maritimeconnectivity.mmtp.SubscribeOrBuilder getSubscribeMessageOrBuilder();

  /**
   * <code>.Unsubscribe unsubscribeMessage = 3;</code>
   * @return Whether the unsubscribeMessage field is set.
   */
  boolean hasUnsubscribeMessage();
  /**
   * <code>.Unsubscribe unsubscribeMessage = 3;</code>
   * @return The unsubscribeMessage.
   */
  net.maritimeconnectivity.mmtp.Unsubscribe getUnsubscribeMessage();
  /**
   * <code>.Unsubscribe unsubscribeMessage = 3;</code>
   */
  net.maritimeconnectivity.mmtp.UnsubscribeOrBuilder getUnsubscribeMessageOrBuilder();

  /**
   * <code>.Send sendMessage = 4;</code>
   * @return Whether the sendMessage field is set.
   */
  boolean hasSendMessage();
  /**
   * <code>.Send sendMessage = 4;</code>
   * @return The sendMessage.
   */
  net.maritimeconnectivity.mmtp.Send getSendMessage();
  /**
   * <code>.Send sendMessage = 4;</code>
   */
  net.maritimeconnectivity.mmtp.SendOrBuilder getSendMessageOrBuilder();

  /**
   * <code>.Receive receiveMessage = 5;</code>
   * @return Whether the receiveMessage field is set.
   */
  boolean hasReceiveMessage();
  /**
   * <code>.Receive receiveMessage = 5;</code>
   * @return The receiveMessage.
   */
  net.maritimeconnectivity.mmtp.Receive getReceiveMessage();
  /**
   * <code>.Receive receiveMessage = 5;</code>
   */
  net.maritimeconnectivity.mmtp.ReceiveOrBuilder getReceiveMessageOrBuilder();

  /**
   * <code>.Fetch fetchMessage = 6;</code>
   * @return Whether the fetchMessage field is set.
   */
  boolean hasFetchMessage();
  /**
   * <code>.Fetch fetchMessage = 6;</code>
   * @return The fetchMessage.
   */
  net.maritimeconnectivity.mmtp.Fetch getFetchMessage();
  /**
   * <code>.Fetch fetchMessage = 6;</code>
   */
  net.maritimeconnectivity.mmtp.FetchOrBuilder getFetchMessageOrBuilder();

  /**
   * <code>.Disconnect disconnectMessage = 7;</code>
   * @return Whether the disconnectMessage field is set.
   */
  boolean hasDisconnectMessage();
  /**
   * <code>.Disconnect disconnectMessage = 7;</code>
   * @return The disconnectMessage.
   */
  net.maritimeconnectivity.mmtp.Disconnect getDisconnectMessage();
  /**
   * <code>.Disconnect disconnectMessage = 7;</code>
   */
  net.maritimeconnectivity.mmtp.DisconnectOrBuilder getDisconnectMessageOrBuilder();

  /**
   * <code>.Connect connectMessage = 8;</code>
   * @return Whether the connectMessage field is set.
   */
  boolean hasConnectMessage();
  /**
   * <code>.Connect connectMessage = 8;</code>
   * @return The connectMessage.
   */
  net.maritimeconnectivity.mmtp.Connect getConnectMessage();
  /**
   * <code>.Connect connectMessage = 8;</code>
   */
  net.maritimeconnectivity.mmtp.ConnectOrBuilder getConnectMessageOrBuilder();

  /**
   * <code>.Notify notifyMessage = 9;</code>
   * @return Whether the notifyMessage field is set.
   */
  boolean hasNotifyMessage();
  /**
   * <code>.Notify notifyMessage = 9;</code>
   * @return The notifyMessage.
   */
  net.maritimeconnectivity.mmtp.Notify getNotifyMessage();
  /**
   * <code>.Notify notifyMessage = 9;</code>
   */
  net.maritimeconnectivity.mmtp.NotifyOrBuilder getNotifyMessageOrBuilder();

  net.maritimeconnectivity.mmtp.ProtocolMessage.BodyCase getBodyCase();
}
