// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code Recipients}
 */
public final class Recipients extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Recipients)
    RecipientsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Recipients.class.getName());
  }
  // Use Recipients.newBuilder() to construct.
  private Recipients(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Recipients() {
    recipients_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Recipients_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Recipients_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.Recipients.class, net.maritimeconnectivity.mmtp.Recipients.Builder.class);
  }

  public static final int RECIPIENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList recipients_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string recipients = 1;</code>
   * @return A list containing the recipients.
   */
  public com.google.protobuf.ProtocolStringList
      getRecipientsList() {
    return recipients_;
  }
  /**
   * <code>repeated string recipients = 1;</code>
   * @return The count of recipients.
   */
  public int getRecipientsCount() {
    return recipients_.size();
  }
  /**
   * <code>repeated string recipients = 1;</code>
   * @param index The index of the element to return.
   * @return The recipients at the given index.
   */
  public java.lang.String getRecipients(int index) {
    return recipients_.get(index);
  }
  /**
   * <code>repeated string recipients = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the recipients at the given index.
   */
  public com.google.protobuf.ByteString
      getRecipientsBytes(int index) {
    return recipients_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recipients_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, recipients_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < recipients_.size(); i++) {
        dataSize += computeStringSizeNoTag(recipients_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRecipientsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.Recipients)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.Recipients other = (net.maritimeconnectivity.mmtp.Recipients) obj;

    if (!getRecipientsList()
        .equals(other.getRecipientsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecipientsCount() > 0) {
      hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRecipientsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.Recipients parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.Recipients parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Recipients parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.Recipients prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Recipients}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Recipients)
      net.maritimeconnectivity.mmtp.RecipientsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Recipients_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Recipients_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.Recipients.class, net.maritimeconnectivity.mmtp.Recipients.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.Recipients.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recipients_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Recipients_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Recipients getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Recipients build() {
      net.maritimeconnectivity.mmtp.Recipients result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.Recipients buildPartial() {
      net.maritimeconnectivity.mmtp.Recipients result = new net.maritimeconnectivity.mmtp.Recipients(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.Recipients result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        recipients_.makeImmutable();
        result.recipients_ = recipients_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.Recipients) {
        return mergeFrom((net.maritimeconnectivity.mmtp.Recipients)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.Recipients other) {
      if (other == net.maritimeconnectivity.mmtp.Recipients.getDefaultInstance()) return this;
      if (!other.recipients_.isEmpty()) {
        if (recipients_.isEmpty()) {
          recipients_ = other.recipients_;
          bitField0_ |= 0x00000001;
        } else {
          ensureRecipientsIsMutable();
          recipients_.addAll(other.recipients_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRecipientsIsMutable();
              recipients_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList recipients_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRecipientsIsMutable() {
      if (!recipients_.isModifiable()) {
        recipients_ = new com.google.protobuf.LazyStringArrayList(recipients_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @return A list containing the recipients.
     */
    public com.google.protobuf.ProtocolStringList
        getRecipientsList() {
      recipients_.makeImmutable();
      return recipients_;
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @return The count of recipients.
     */
    public int getRecipientsCount() {
      return recipients_.size();
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @param index The index of the element to return.
     * @return The recipients at the given index.
     */
    public java.lang.String getRecipients(int index) {
      return recipients_.get(index);
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the recipients at the given index.
     */
    public com.google.protobuf.ByteString
        getRecipientsBytes(int index) {
      return recipients_.getByteString(index);
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @param index The index to set the value at.
     * @param value The recipients to set.
     * @return This builder for chaining.
     */
    public Builder setRecipients(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRecipientsIsMutable();
      recipients_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @param value The recipients to add.
     * @return This builder for chaining.
     */
    public Builder addRecipients(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRecipientsIsMutable();
      recipients_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @param values The recipients to add.
     * @return This builder for chaining.
     */
    public Builder addAllRecipients(
        java.lang.Iterable<java.lang.String> values) {
      ensureRecipientsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, recipients_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipients() {
      recipients_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string recipients = 1;</code>
     * @param value The bytes of the recipients to add.
     * @return This builder for chaining.
     */
    public Builder addRecipientsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRecipientsIsMutable();
      recipients_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Recipients)
  }

  // @@protoc_insertion_point(class_scope:Recipients)
  private static final net.maritimeconnectivity.mmtp.Recipients DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.Recipients();
  }

  public static net.maritimeconnectivity.mmtp.Recipients getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Recipients>
      PARSER = new com.google.protobuf.AbstractParser<Recipients>() {
    @java.lang.Override
    public Recipients parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Recipients> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Recipients> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.Recipients getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

