// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf enum {@code ResponseEnum}
 */
public enum ResponseEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNSPECIFIED_RESPONSE = 0;</code>
   */
  UNSPECIFIED_RESPONSE(0),
  /**
   * <code>GOOD = 1;</code>
   */
  GOOD(1),
  /**
   * <code>ERROR = 2;</code>
   */
  ERROR(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ResponseEnum.class.getName());
  }
  /**
   * <code>UNSPECIFIED_RESPONSE = 0;</code>
   */
  public static final int UNSPECIFIED_RESPONSE_VALUE = 0;
  /**
   * <code>GOOD = 1;</code>
   */
  public static final int GOOD_VALUE = 1;
  /**
   * <code>ERROR = 2;</code>
   */
  public static final int ERROR_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ResponseEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ResponseEnum forNumber(int value) {
    switch (value) {
      case 0: return UNSPECIFIED_RESPONSE;
      case 1: return GOOD;
      case 2: return ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResponseEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResponseEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResponseEnum>() {
          public ResponseEnum findValueByNumber(int number) {
            return ResponseEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.getDescriptor().getEnumTypes().get(2);
  }

  private static final ResponseEnum[] VALUES = values();

  public static ResponseEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResponseEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ResponseEnum)
}

