// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseToUuid = 1;</code>
   * @return The responseToUuid.
   */
  java.lang.String getResponseToUuid();
  /**
   * <code>string responseToUuid = 1;</code>
   * @return The bytes for responseToUuid.
   */
  com.google.protobuf.ByteString
      getResponseToUuidBytes();

  /**
   * <code>.ResponseEnum response = 2;</code>
   * @return The enum numeric value on the wire for response.
   */
  int getResponseValue();
  /**
   * <code>.ResponseEnum response = 2;</code>
   * @return The response.
   */
  net.maritimeconnectivity.mmtp.ResponseEnum getResponse();

  /**
   * <code>optional string reasonText = 3;</code>
   * @return Whether the reasonText field is set.
   */
  boolean hasReasonText();
  /**
   * <code>optional string reasonText = 3;</code>
   * @return The reasonText.
   */
  java.lang.String getReasonText();
  /**
   * <code>optional string reasonText = 3;</code>
   * @return The bytes for reasonText.
   */
  com.google.protobuf.ByteString
      getReasonTextBytes();

  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> 
      getMessageMetadataList();
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  net.maritimeconnectivity.mmtp.MessageMetadata getMessageMetadata(int index);
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  int getMessageMetadataCount();
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  java.util.List<? extends net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
      getMessageMetadataOrBuilderList();
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder getMessageMetadataOrBuilder(
      int index);

  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  java.util.List<net.maritimeconnectivity.mmtp.MessageContent> 
      getMessageContentList();
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  net.maritimeconnectivity.mmtp.MessageContent getMessageContent(int index);
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  int getMessageContentCount();
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  java.util.List<? extends net.maritimeconnectivity.mmtp.MessageContentOrBuilder> 
      getMessageContentOrBuilderList();
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  net.maritimeconnectivity.mmtp.MessageContentOrBuilder getMessageContentOrBuilder(
      int index);

  /**
   * <code>optional string reconnectToken = 6;</code>
   * @return Whether the reconnectToken field is set.
   */
  boolean hasReconnectToken();
  /**
   * <code>optional string reconnectToken = 6;</code>
   * @return The reconnectToken.
   */
  java.lang.String getReconnectToken();
  /**
   * <code>optional string reconnectToken = 6;</code>
   * @return The bytes for reconnectToken.
   */
  com.google.protobuf.ByteString
      getReconnectTokenBytes();
}
