// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code ResponseMessage}
 */
public final class ResponseMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ResponseMessage)
    ResponseMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ResponseMessage.class.getName());
  }
  // Use ResponseMessage.newBuilder() to construct.
  private ResponseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResponseMessage() {
    responseToUuid_ = "";
    response_ = 0;
    reasonText_ = "";
    messageMetadata_ = java.util.Collections.emptyList();
    messageContent_ = java.util.Collections.emptyList();
    reconnectToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ResponseMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ResponseMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.ResponseMessage.class, net.maritimeconnectivity.mmtp.ResponseMessage.Builder.class);
  }

  private int bitField0_;
  public static final int RESPONSETOUUID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object responseToUuid_ = "";
  /**
   * <code>string responseToUuid = 1;</code>
   * @return The responseToUuid.
   */
  @java.lang.Override
  public java.lang.String getResponseToUuid() {
    java.lang.Object ref = responseToUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseToUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string responseToUuid = 1;</code>
   * @return The bytes for responseToUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseToUuidBytes() {
    java.lang.Object ref = responseToUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseToUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private int response_ = 0;
  /**
   * <code>.ResponseEnum response = 2;</code>
   * @return The enum numeric value on the wire for response.
   */
  @java.lang.Override public int getResponseValue() {
    return response_;
  }
  /**
   * <code>.ResponseEnum response = 2;</code>
   * @return The response.
   */
  @java.lang.Override public net.maritimeconnectivity.mmtp.ResponseEnum getResponse() {
    net.maritimeconnectivity.mmtp.ResponseEnum result = net.maritimeconnectivity.mmtp.ResponseEnum.forNumber(response_);
    return result == null ? net.maritimeconnectivity.mmtp.ResponseEnum.UNRECOGNIZED : result;
  }

  public static final int REASONTEXT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reasonText_ = "";
  /**
   * <code>optional string reasonText = 3;</code>
   * @return Whether the reasonText field is set.
   */
  @java.lang.Override
  public boolean hasReasonText() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string reasonText = 3;</code>
   * @return The reasonText.
   */
  @java.lang.Override
  public java.lang.String getReasonText() {
    java.lang.Object ref = reasonText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reasonText_ = s;
      return s;
    }
  }
  /**
   * <code>optional string reasonText = 3;</code>
   * @return The bytes for reasonText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonTextBytes() {
    java.lang.Object ref = reasonText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reasonText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGEMETADATA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> messageMetadata_;
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  @java.lang.Override
  public java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> getMessageMetadataList() {
    return messageMetadata_;
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
      getMessageMetadataOrBuilderList() {
    return messageMetadata_;
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  @java.lang.Override
  public int getMessageMetadataCount() {
    return messageMetadata_.size();
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MessageMetadata getMessageMetadata(int index) {
    return messageMetadata_.get(index);
  }
  /**
   * <code>repeated .MessageMetadata messageMetadata = 4;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder getMessageMetadataOrBuilder(
      int index) {
    return messageMetadata_.get(index);
  }

  public static final int MESSAGECONTENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<net.maritimeconnectivity.mmtp.MessageContent> messageContent_;
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  @java.lang.Override
  public java.util.List<net.maritimeconnectivity.mmtp.MessageContent> getMessageContentList() {
    return messageContent_;
  }
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.maritimeconnectivity.mmtp.MessageContentOrBuilder> 
      getMessageContentOrBuilderList() {
    return messageContent_;
  }
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  @java.lang.Override
  public int getMessageContentCount() {
    return messageContent_.size();
  }
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MessageContent getMessageContent(int index) {
    return messageContent_.get(index);
  }
  /**
   * <code>repeated .MessageContent messageContent = 5;</code>
   */
  @java.lang.Override
  public net.maritimeconnectivity.mmtp.MessageContentOrBuilder getMessageContentOrBuilder(
      int index) {
    return messageContent_.get(index);
  }

  public static final int RECONNECTTOKEN_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reconnectToken_ = "";
  /**
   * <code>optional string reconnectToken = 6;</code>
   * @return Whether the reconnectToken field is set.
   */
  @java.lang.Override
  public boolean hasReconnectToken() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string reconnectToken = 6;</code>
   * @return The reconnectToken.
   */
  @java.lang.Override
  public java.lang.String getReconnectToken() {
    java.lang.Object ref = reconnectToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reconnectToken_ = s;
      return s;
    }
  }
  /**
   * <code>optional string reconnectToken = 6;</code>
   * @return The bytes for reconnectToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReconnectTokenBytes() {
    java.lang.Object ref = reconnectToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reconnectToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseToUuid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, responseToUuid_);
    }
    if (response_ != net.maritimeconnectivity.mmtp.ResponseEnum.UNSPECIFIED_RESPONSE.getNumber()) {
      output.writeEnum(2, response_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, reasonText_);
    }
    for (int i = 0; i < messageMetadata_.size(); i++) {
      output.writeMessage(4, messageMetadata_.get(i));
    }
    for (int i = 0; i < messageContent_.size(); i++) {
      output.writeMessage(5, messageContent_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, reconnectToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseToUuid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, responseToUuid_);
    }
    if (response_ != net.maritimeconnectivity.mmtp.ResponseEnum.UNSPECIFIED_RESPONSE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, response_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, reasonText_);
    }
    for (int i = 0; i < messageMetadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, messageMetadata_.get(i));
    }
    for (int i = 0; i < messageContent_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, messageContent_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, reconnectToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.ResponseMessage)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.ResponseMessage other = (net.maritimeconnectivity.mmtp.ResponseMessage) obj;

    if (!getResponseToUuid()
        .equals(other.getResponseToUuid())) return false;
    if (response_ != other.response_) return false;
    if (hasReasonText() != other.hasReasonText()) return false;
    if (hasReasonText()) {
      if (!getReasonText()
          .equals(other.getReasonText())) return false;
    }
    if (!getMessageMetadataList()
        .equals(other.getMessageMetadataList())) return false;
    if (!getMessageContentList()
        .equals(other.getMessageContentList())) return false;
    if (hasReconnectToken() != other.hasReconnectToken()) return false;
    if (hasReconnectToken()) {
      if (!getReconnectToken()
          .equals(other.getReconnectToken())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSETOUUID_FIELD_NUMBER;
    hash = (53 * hash) + getResponseToUuid().hashCode();
    hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + response_;
    if (hasReasonText()) {
      hash = (37 * hash) + REASONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getReasonText().hashCode();
    }
    if (getMessageMetadataCount() > 0) {
      hash = (37 * hash) + MESSAGEMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMessageMetadataList().hashCode();
    }
    if (getMessageContentCount() > 0) {
      hash = (37 * hash) + MESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageContentList().hashCode();
    }
    if (hasReconnectToken()) {
      hash = (37 * hash) + RECONNECTTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getReconnectToken().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.ResponseMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.ResponseMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.ResponseMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResponseMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResponseMessage)
      net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.ResponseMessage.class, net.maritimeconnectivity.mmtp.ResponseMessage.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.ResponseMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      responseToUuid_ = "";
      response_ = 0;
      reasonText_ = "";
      if (messageMetadataBuilder_ == null) {
        messageMetadata_ = java.util.Collections.emptyList();
      } else {
        messageMetadata_ = null;
        messageMetadataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (messageContentBuilder_ == null) {
        messageContent_ = java.util.Collections.emptyList();
      } else {
        messageContent_ = null;
        messageContentBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      reconnectToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_ResponseMessage_descriptor;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ResponseMessage getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance();
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ResponseMessage build() {
      net.maritimeconnectivity.mmtp.ResponseMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ResponseMessage buildPartial() {
      net.maritimeconnectivity.mmtp.ResponseMessage result = new net.maritimeconnectivity.mmtp.ResponseMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(net.maritimeconnectivity.mmtp.ResponseMessage result) {
      if (messageMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          messageMetadata_ = java.util.Collections.unmodifiableList(messageMetadata_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.messageMetadata_ = messageMetadata_;
      } else {
        result.messageMetadata_ = messageMetadataBuilder_.build();
      }
      if (messageContentBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          messageContent_ = java.util.Collections.unmodifiableList(messageContent_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.messageContent_ = messageContent_;
      } else {
        result.messageContent_ = messageContentBuilder_.build();
      }
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.ResponseMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.responseToUuid_ = responseToUuid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.response_ = response_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reasonText_ = reasonText_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.reconnectToken_ = reconnectToken_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.ResponseMessage) {
        return mergeFrom((net.maritimeconnectivity.mmtp.ResponseMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.ResponseMessage other) {
      if (other == net.maritimeconnectivity.mmtp.ResponseMessage.getDefaultInstance()) return this;
      if (!other.getResponseToUuid().isEmpty()) {
        responseToUuid_ = other.responseToUuid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.response_ != 0) {
        setResponseValue(other.getResponseValue());
      }
      if (other.hasReasonText()) {
        reasonText_ = other.reasonText_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (messageMetadataBuilder_ == null) {
        if (!other.messageMetadata_.isEmpty()) {
          if (messageMetadata_.isEmpty()) {
            messageMetadata_ = other.messageMetadata_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMessageMetadataIsMutable();
            messageMetadata_.addAll(other.messageMetadata_);
          }
          onChanged();
        }
      } else {
        if (!other.messageMetadata_.isEmpty()) {
          if (messageMetadataBuilder_.isEmpty()) {
            messageMetadataBuilder_.dispose();
            messageMetadataBuilder_ = null;
            messageMetadata_ = other.messageMetadata_;
            bitField0_ = (bitField0_ & ~0x00000008);
            messageMetadataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMessageMetadataFieldBuilder() : null;
          } else {
            messageMetadataBuilder_.addAllMessages(other.messageMetadata_);
          }
        }
      }
      if (messageContentBuilder_ == null) {
        if (!other.messageContent_.isEmpty()) {
          if (messageContent_.isEmpty()) {
            messageContent_ = other.messageContent_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureMessageContentIsMutable();
            messageContent_.addAll(other.messageContent_);
          }
          onChanged();
        }
      } else {
        if (!other.messageContent_.isEmpty()) {
          if (messageContentBuilder_.isEmpty()) {
            messageContentBuilder_.dispose();
            messageContentBuilder_ = null;
            messageContent_ = other.messageContent_;
            bitField0_ = (bitField0_ & ~0x00000010);
            messageContentBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMessageContentFieldBuilder() : null;
          } else {
            messageContentBuilder_.addAllMessages(other.messageContent_);
          }
        }
      }
      if (other.hasReconnectToken()) {
        reconnectToken_ = other.reconnectToken_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              responseToUuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              response_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              reasonText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              net.maritimeconnectivity.mmtp.MessageMetadata m =
                  input.readMessage(
                      net.maritimeconnectivity.mmtp.MessageMetadata.parser(),
                      extensionRegistry);
              if (messageMetadataBuilder_ == null) {
                ensureMessageMetadataIsMutable();
                messageMetadata_.add(m);
              } else {
                messageMetadataBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              net.maritimeconnectivity.mmtp.MessageContent m =
                  input.readMessage(
                      net.maritimeconnectivity.mmtp.MessageContent.parser(),
                      extensionRegistry);
              if (messageContentBuilder_ == null) {
                ensureMessageContentIsMutable();
                messageContent_.add(m);
              } else {
                messageContentBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              reconnectToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object responseToUuid_ = "";
    /**
     * <code>string responseToUuid = 1;</code>
     * @return The responseToUuid.
     */
    public java.lang.String getResponseToUuid() {
      java.lang.Object ref = responseToUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseToUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string responseToUuid = 1;</code>
     * @return The bytes for responseToUuid.
     */
    public com.google.protobuf.ByteString
        getResponseToUuidBytes() {
      java.lang.Object ref = responseToUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseToUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string responseToUuid = 1;</code>
     * @param value The responseToUuid to set.
     * @return This builder for chaining.
     */
    public Builder setResponseToUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      responseToUuid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string responseToUuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseToUuid() {
      responseToUuid_ = getDefaultInstance().getResponseToUuid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string responseToUuid = 1;</code>
     * @param value The bytes for responseToUuid to set.
     * @return This builder for chaining.
     */
    public Builder setResponseToUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responseToUuid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int response_ = 0;
    /**
     * <code>.ResponseEnum response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    @java.lang.Override public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.ResponseEnum response = 2;</code>
     * @param value The enum numeric value on the wire for response to set.
     * @return This builder for chaining.
     */
    public Builder setResponseValue(int value) {
      response_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ResponseEnum response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public net.maritimeconnectivity.mmtp.ResponseEnum getResponse() {
      net.maritimeconnectivity.mmtp.ResponseEnum result = net.maritimeconnectivity.mmtp.ResponseEnum.forNumber(response_);
      return result == null ? net.maritimeconnectivity.mmtp.ResponseEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.ResponseEnum response = 2;</code>
     * @param value The response to set.
     * @return This builder for chaining.
     */
    public Builder setResponse(net.maritimeconnectivity.mmtp.ResponseEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      response_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ResponseEnum response = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000002);
      response_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reasonText_ = "";
    /**
     * <code>optional string reasonText = 3;</code>
     * @return Whether the reasonText field is set.
     */
    public boolean hasReasonText() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string reasonText = 3;</code>
     * @return The reasonText.
     */
    public java.lang.String getReasonText() {
      java.lang.Object ref = reasonText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reasonText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string reasonText = 3;</code>
     * @return The bytes for reasonText.
     */
    public com.google.protobuf.ByteString
        getReasonTextBytes() {
      java.lang.Object ref = reasonText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reasonText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reasonText = 3;</code>
     * @param value The reasonText to set.
     * @return This builder for chaining.
     */
    public Builder setReasonText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reasonText_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reasonText = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasonText() {
      reasonText_ = getDefaultInstance().getReasonText();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string reasonText = 3;</code>
     * @param value The bytes for reasonText to set.
     * @return This builder for chaining.
     */
    public Builder setReasonTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reasonText_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> messageMetadata_ =
      java.util.Collections.emptyList();
    private void ensureMessageMetadataIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        messageMetadata_ = new java.util.ArrayList<net.maritimeconnectivity.mmtp.MessageMetadata>(messageMetadata_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        net.maritimeconnectivity.mmtp.MessageMetadata, net.maritimeconnectivity.mmtp.MessageMetadata.Builder, net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> messageMetadataBuilder_;

    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata> getMessageMetadataList() {
      if (messageMetadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messageMetadata_);
      } else {
        return messageMetadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public int getMessageMetadataCount() {
      if (messageMetadataBuilder_ == null) {
        return messageMetadata_.size();
      } else {
        return messageMetadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata getMessageMetadata(int index) {
      if (messageMetadataBuilder_ == null) {
        return messageMetadata_.get(index);
      } else {
        return messageMetadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder setMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata value) {
      if (messageMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageMetadataIsMutable();
        messageMetadata_.set(index, value);
        onChanged();
      } else {
        messageMetadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder setMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata.Builder builderForValue) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageMetadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder addMessageMetadata(net.maritimeconnectivity.mmtp.MessageMetadata value) {
      if (messageMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(value);
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder addMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata value) {
      if (messageMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(index, value);
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder addMessageMetadata(
        net.maritimeconnectivity.mmtp.MessageMetadata.Builder builderForValue) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(builderForValue.build());
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder addMessageMetadata(
        int index, net.maritimeconnectivity.mmtp.MessageMetadata.Builder builderForValue) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageMetadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder addAllMessageMetadata(
        java.lang.Iterable<? extends net.maritimeconnectivity.mmtp.MessageMetadata> values) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageMetadata_);
        onChanged();
      } else {
        messageMetadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder clearMessageMetadata() {
      if (messageMetadataBuilder_ == null) {
        messageMetadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        messageMetadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public Builder removeMessageMetadata(int index) {
      if (messageMetadataBuilder_ == null) {
        ensureMessageMetadataIsMutable();
        messageMetadata_.remove(index);
        onChanged();
      } else {
        messageMetadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata.Builder getMessageMetadataBuilder(
        int index) {
      return getMessageMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder getMessageMetadataOrBuilder(
        int index) {
      if (messageMetadataBuilder_ == null) {
        return messageMetadata_.get(index);  } else {
        return messageMetadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public java.util.List<? extends net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
         getMessageMetadataOrBuilderList() {
      if (messageMetadataBuilder_ != null) {
        return messageMetadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messageMetadata_);
      }
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata.Builder addMessageMetadataBuilder() {
      return getMessageMetadataFieldBuilder().addBuilder(
          net.maritimeconnectivity.mmtp.MessageMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageMetadata.Builder addMessageMetadataBuilder(
        int index) {
      return getMessageMetadataFieldBuilder().addBuilder(
          index, net.maritimeconnectivity.mmtp.MessageMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageMetadata messageMetadata = 4;</code>
     */
    public java.util.List<net.maritimeconnectivity.mmtp.MessageMetadata.Builder> 
         getMessageMetadataBuilderList() {
      return getMessageMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        net.maritimeconnectivity.mmtp.MessageMetadata, net.maritimeconnectivity.mmtp.MessageMetadata.Builder, net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder> 
        getMessageMetadataFieldBuilder() {
      if (messageMetadataBuilder_ == null) {
        messageMetadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            net.maritimeconnectivity.mmtp.MessageMetadata, net.maritimeconnectivity.mmtp.MessageMetadata.Builder, net.maritimeconnectivity.mmtp.MessageMetadataOrBuilder>(
                messageMetadata_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        messageMetadata_ = null;
      }
      return messageMetadataBuilder_;
    }

    private java.util.List<net.maritimeconnectivity.mmtp.MessageContent> messageContent_ =
      java.util.Collections.emptyList();
    private void ensureMessageContentIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        messageContent_ = new java.util.ArrayList<net.maritimeconnectivity.mmtp.MessageContent>(messageContent_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        net.maritimeconnectivity.mmtp.MessageContent, net.maritimeconnectivity.mmtp.MessageContent.Builder, net.maritimeconnectivity.mmtp.MessageContentOrBuilder> messageContentBuilder_;

    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public java.util.List<net.maritimeconnectivity.mmtp.MessageContent> getMessageContentList() {
      if (messageContentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messageContent_);
      } else {
        return messageContentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public int getMessageContentCount() {
      if (messageContentBuilder_ == null) {
        return messageContent_.size();
      } else {
        return messageContentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageContent getMessageContent(int index) {
      if (messageContentBuilder_ == null) {
        return messageContent_.get(index);
      } else {
        return messageContentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder setMessageContent(
        int index, net.maritimeconnectivity.mmtp.MessageContent value) {
      if (messageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageContentIsMutable();
        messageContent_.set(index, value);
        onChanged();
      } else {
        messageContentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder setMessageContent(
        int index, net.maritimeconnectivity.mmtp.MessageContent.Builder builderForValue) {
      if (messageContentBuilder_ == null) {
        ensureMessageContentIsMutable();
        messageContent_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageContentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder addMessageContent(net.maritimeconnectivity.mmtp.MessageContent value) {
      if (messageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageContentIsMutable();
        messageContent_.add(value);
        onChanged();
      } else {
        messageContentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder addMessageContent(
        int index, net.maritimeconnectivity.mmtp.MessageContent value) {
      if (messageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageContentIsMutable();
        messageContent_.add(index, value);
        onChanged();
      } else {
        messageContentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder addMessageContent(
        net.maritimeconnectivity.mmtp.MessageContent.Builder builderForValue) {
      if (messageContentBuilder_ == null) {
        ensureMessageContentIsMutable();
        messageContent_.add(builderForValue.build());
        onChanged();
      } else {
        messageContentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder addMessageContent(
        int index, net.maritimeconnectivity.mmtp.MessageContent.Builder builderForValue) {
      if (messageContentBuilder_ == null) {
        ensureMessageContentIsMutable();
        messageContent_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageContentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder addAllMessageContent(
        java.lang.Iterable<? extends net.maritimeconnectivity.mmtp.MessageContent> values) {
      if (messageContentBuilder_ == null) {
        ensureMessageContentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageContent_);
        onChanged();
      } else {
        messageContentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder clearMessageContent() {
      if (messageContentBuilder_ == null) {
        messageContent_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        messageContentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public Builder removeMessageContent(int index) {
      if (messageContentBuilder_ == null) {
        ensureMessageContentIsMutable();
        messageContent_.remove(index);
        onChanged();
      } else {
        messageContentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageContent.Builder getMessageContentBuilder(
        int index) {
      return getMessageContentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageContentOrBuilder getMessageContentOrBuilder(
        int index) {
      if (messageContentBuilder_ == null) {
        return messageContent_.get(index);  } else {
        return messageContentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public java.util.List<? extends net.maritimeconnectivity.mmtp.MessageContentOrBuilder> 
         getMessageContentOrBuilderList() {
      if (messageContentBuilder_ != null) {
        return messageContentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messageContent_);
      }
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageContent.Builder addMessageContentBuilder() {
      return getMessageContentFieldBuilder().addBuilder(
          net.maritimeconnectivity.mmtp.MessageContent.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public net.maritimeconnectivity.mmtp.MessageContent.Builder addMessageContentBuilder(
        int index) {
      return getMessageContentFieldBuilder().addBuilder(
          index, net.maritimeconnectivity.mmtp.MessageContent.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageContent messageContent = 5;</code>
     */
    public java.util.List<net.maritimeconnectivity.mmtp.MessageContent.Builder> 
         getMessageContentBuilderList() {
      return getMessageContentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        net.maritimeconnectivity.mmtp.MessageContent, net.maritimeconnectivity.mmtp.MessageContent.Builder, net.maritimeconnectivity.mmtp.MessageContentOrBuilder> 
        getMessageContentFieldBuilder() {
      if (messageContentBuilder_ == null) {
        messageContentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            net.maritimeconnectivity.mmtp.MessageContent, net.maritimeconnectivity.mmtp.MessageContent.Builder, net.maritimeconnectivity.mmtp.MessageContentOrBuilder>(
                messageContent_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        messageContent_ = null;
      }
      return messageContentBuilder_;
    }

    private java.lang.Object reconnectToken_ = "";
    /**
     * <code>optional string reconnectToken = 6;</code>
     * @return Whether the reconnectToken field is set.
     */
    public boolean hasReconnectToken() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string reconnectToken = 6;</code>
     * @return The reconnectToken.
     */
    public java.lang.String getReconnectToken() {
      java.lang.Object ref = reconnectToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reconnectToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string reconnectToken = 6;</code>
     * @return The bytes for reconnectToken.
     */
    public com.google.protobuf.ByteString
        getReconnectTokenBytes() {
      java.lang.Object ref = reconnectToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reconnectToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reconnectToken = 6;</code>
     * @param value The reconnectToken to set.
     * @return This builder for chaining.
     */
    public Builder setReconnectToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reconnectToken_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reconnectToken = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReconnectToken() {
      reconnectToken_ = getDefaultInstance().getReconnectToken();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string reconnectToken = 6;</code>
     * @param value The bytes for reconnectToken to set.
     * @return This builder for chaining.
     */
    public Builder setReconnectTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reconnectToken_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ResponseMessage)
  }

  // @@protoc_insertion_point(class_scope:ResponseMessage)
  private static final net.maritimeconnectivity.mmtp.ResponseMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.ResponseMessage();
  }

  public static net.maritimeconnectivity.mmtp.ResponseMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseMessage>
      PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
    @java.lang.Override
    public ResponseMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResponseMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.maritimeconnectivity.mmtp.ResponseMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

