// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.29.3

package net.maritimeconnectivity.mmtp;

public interface SubscribeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Subscribe)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subject = 1;</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <code>string subject = 1;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 1;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>bool directMessages = 2;</code>
   * @return Whether the directMessages field is set.
   */
  boolean hasDirectMessages();
  /**
   * <code>bool directMessages = 2;</code>
   * @return The directMessages.
   */
  boolean getDirectMessages();

  net.maritimeconnectivity.mmtp.Subscribe.SubjectOrDirectMessagesCase getSubjectOrDirectMessagesCase();
}
